/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Angry_Birds.java
 *
 * Created on Nov 12, 2011, 6:19:19 PM
 */
package Simple_Games;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author $Akshay$
 */
@SuppressWarnings("serial")
public class Angry_Birds extends javax.swing.JFrame {

    /** Creates new form Angry_Birds */
    public Angry_Birds() {
        initComponents();
        drawpanel.setBackground(new Color(249,239,211));
        scroll.setViewportView(drawpanel);
        drawpanel.repaint();
        
Timer time = new Timer(20,new ActionListener(){
 public void actionPerformed(ActionEvent evt) {
     
     if(x>=600)
     {
         
     scr.setLocation(scrx,scry);
     }
   if(flyable==true){
       
     if((y>=365)&&(ux>0))//Friction after Reaching Ground
     ux=(int)(ux+f);
     
     if((y>=370)&&(uy>0))
     {
     t=0;
     tempy=369;
     uy=uy*6/10;
     }
     
     x=x+ux/4;
     y=(int)(tempy-(uy*t)-(g*t*t/2));
     if(y>=370)
     y=370;
     t=(float)(t+0.20);
     bird.setLocation(x,y);


     
  }
 
 }});
time.start();
Timer developer = new Timer(100,new ActionListener(){
 public void actionPerformed(ActionEvent evt) {
birdx.setValue(x);
birdy.setValue(y);
  
}});
if(developer_mode==true) {
            developer.start();
        }
    }

  
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bird = new javax.swing.JLabel();
        scr = new javax.swing.JPanel();
        dev_off = new javax.swing.JButton();
        dev_on = new javax.swing.JButton();
        pad = new javax.swing.JLabel();
        launch_ground = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        ground = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        BG = new javax.swing.JLabel();
        dev = new javax.swing.JPanel();
        birdx = new javax.swing.JSpinner();
        birdy = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bird.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bird.gif"))); // NOI18N
        bird.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bird.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                birdMouseReleased(evt);
            }
        });
        bird.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                birdMouseDragged(evt);
            }
        });
        getContentPane().add(bird, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 50));

        scr.setOpaque(false);
        scr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dev_off.setBackground(new java.awt.Color(204, 0, 0));
        dev_off.setForeground(new java.awt.Color(204, 0, 0));
        dev_off.setToolTipText("");
        dev_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dev_offActionPerformed(evt);
            }
        });
        scr.add(dev_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 5, 5));

        dev_on.setBackground(new java.awt.Color(0, 204, 51));
        dev_on.setForeground(new java.awt.Color(0, 204, 51));
        dev_on.setToolTipText("");
        dev_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dev_onActionPerformed(evt);
            }
        });
        scr.add(dev_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 5, 5));

        pad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catapult.png"))); // NOI18N
        pad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        scr.add(pad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, 110));

        launch_ground.setBackground(new java.awt.Color(145, 74, 38));
        launch_ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ground_launch_pad.png"))); // NOI18N
        scr.add(launch_ground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, 130, 115));

        scroll.setBackground(new java.awt.Color(255, 245, 208));
        scroll.setBorder(null);
        scr.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, 110));

        ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ground.png"))); // NOI18N
        scr.add(ground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1350, 90));

        getContentPane().add(scr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 500));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("By - $Dollar Akshay$ ©");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 210, 60));

        reset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 51, 51));
        reset.setText("Bring back the Chick !!");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 280, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/angry_birds_bg.png"))); // NOI18N
        BG.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 410));

        dev.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Developer's Area", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("256 Bytes", 0, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        dev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        birdx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        birdx.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(30), Integer.valueOf(0), null, Integer.valueOf(1)));
        birdx.setFocusable(false);
        dev.add(birdx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));

        birdy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        birdy.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(30), Integer.valueOf(0), null, Integer.valueOf(1)));
        birdy.setFocusable(false);
        dev.add(birdy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bird Location :");
        dev.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 30));

        getContentPane().add(dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1350, 0));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public final class InnerClassDrawingPanel extends javax.swing.JPanel {    
          protected void paintComponent(Graphics g) {
       Graphics2D g2d = (Graphics2D)g;
         g2d.clearRect(0, 0, 120, 110);     
        super.paintComponent(g2d);
        
        g2d.setColor(new Color(50,0,0));
        g2d.setBackground(new Color(240,216,130));
        g2d.setStroke(new BasicStroke(7F));
        g2d.drawLine(bird.getX()+20,bird.getY()-245,105,20);
        g2d.setStroke(new BasicStroke(9F));
        g2d.drawLine(bird.getX()+20,bird.getY()-245,85,20);
          }
    }
    
int x=30,y=300;//Primary Location of the Angry Bird
int tempx,tempy;//Temporary Varialbes
int mx,my;
int ux,uy;//Initial Velocity along x→ and y↑ component
int scrx=0,scry=0;//
float scrdx =0;//Rate at which screen Moves 
float t=0;
final int g=-5;//Gravity
final float f =(float)-0.5;//Friction
boolean developer_mode=true;
boolean flyable,mouserelease=false,fall=false;




    private void birdMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birdMouseDragged
repaint();
        x =bird.getX();
y =bird.getY();
mx = getMousePosition().x-30;
my = getMousePosition().y-50;

if(mx<=pad.getX())
mx=pad.getX();
else if(mx>pad.getX()+pad.getWidth()-50)
mx=pad.getX()+pad.getWidth()-50;
if(my<=pad.getY())
my=pad.getY();
else if(my>pad.getY()+pad.getHeight()-50)
my=pad.getY()+pad.getHeight()-50;
bird.setLocation(mx,my); 
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
    }//GEN-LAST:event_birdMouseDragged

    private void birdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birdMouseReleased
ux =Math.abs(bird.getX()-pad.getX()-70);
uy =bird.getY()-pad.getY();
x =bird.getX();
tempy =bird.getY();
flyable=true;
    }//GEN-LAST:event_birdMouseReleased

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
flyable=false;        
t=0;
scrx=0;
scr.setLocation(0,0);
x=pad.getX()+10;y=pad.getY()+10;
bird.setLocation(x,y); 

    }//GEN-LAST:event_resetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void dev_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dev_onActionPerformed

if(developer_mode==true)
{
setSize(1350,638);
dev.setSize(1350,100);
}

   // TODO add your handling code here:
    }//GEN-LAST:event_dev_onActionPerformed

    private void dev_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dev_offActionPerformed
if(developer_mode==true)
{
setSize(1350,538);
dev.setSize(1350,0);
}
        
    }//GEN-LAST:event_dev_offActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Angry_Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Angry_Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Angry_Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Angry_Birds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Angry_Birds().setVisible(true);
            }
        });
    }
    
    private InnerClassDrawingPanel drawpanel = new InnerClassDrawingPanel();;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel bird;
    private javax.swing.JSpinner birdx;
    private javax.swing.JSpinner birdy;
    private javax.swing.JPanel dev;
    private javax.swing.JButton dev_off;
    private javax.swing.JButton dev_on;
    private javax.swing.JLabel ground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel launch_ground;
    private javax.swing.JLabel pad;
    private javax.swing.JButton reset;
    private javax.swing.JPanel scr;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
