/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Simple_Games;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author $Akshay$
 */
public class Platform_Game extends javax.swing.JFrame {

    /**
     * Creates new form Platform_Game
     */
    public Platform_Game() {
        initComponents();
Timer t;
t = new Timer(25,new ActionListener(){
public void actionPerformed (ActionEvent e)
{
int posx=Man.getX(),posy=Man.getY();
int width=Man.getWidth(),height=Man.getHeight();
if(left)
posx-=x_velocity;
if(right)
posx+=x_velocity;
if((jump==true)&&(onGround()==true)&&(y_velocity==0)){
y_velocity=-15;
}
if(onGround()==false)
y_velocity+=gravity;

posy+=y_velocity;

for(int i=1;i<Screen.getComponentCount();i++)
{
Component c = Screen.getComponent(i);

if(c.getName().equals("ground")){
    
if((posy+man_height-y_velocity<=c.getY())
   &&(posy+man_height>=c.getY()) 
   &&(posx+man_width>c.getX()) 
   &&(posx<c.getX()+c.getWidth())){

jump=false;
y_velocity=0;
posy=c.getY()-man_height;

}
else if((posy-y_velocity>=c.getY()+c.getHeight())&&
(posx!=c.getX()+c.getWidth())&&
(posx+man_width!=c.getX())&&
(c.getBounds().intersectsLine(posx,posy,posx+man_width,posy))){
y_velocity=0;
posy=c.getY()+c.getHeight();
}

else if(new Rectangle(posx,posy,man_width,man_height).intersectsLine(c.getX(),c.getY(),c.getX(),c.getY()+c.getHeight())){
posx=c.getX()-man_width;
}

else if(new Rectangle(posx,posy,man_width,man_height).intersectsLine(c.getX()+c.getWidth(),c.getY(),c.getX()+c.getWidth(),c.getY()+c.getHeight())){
posx=c.getX()+c.getWidth();
}
if(c.getY()!=430){
c.setLocation(c.getX(),c.getY());
if(c.getX()+c.getWidth()<0){
Random r = new Random();
int y = r.nextInt(320)+110;
c.setLocation(600,y);
int w = r.nextInt(30)+50;
int h = r.nextInt(20)+10;
c.setSize(w,h);
}
}
}
}

if(posx+man_width>=BG.getWidth()){
System.out.println((posx+man_width)+" , "+Screen.getWidth());
posx=BG.getWidth()-man_width;
}
else if(posx<0)
posx=0;

if(posy+man_height>=BG.getHeight())
posy=BG.getHeight()-man_height-2;
else if(posy<0){
posy=0;
y_velocity=0;
}

Man.setLocation(posx, posy);

}});
t.start();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Screen = new javax.swing.JPanel();
        Man = new javax.swing.JLabel();
        Ground = new javax.swing.JLabel();
        Blocks = new javax.swing.JLabel();
        Blocks4 = new javax.swing.JLabel();
        Blocks1 = new javax.swing.JLabel();
        Blocks3 = new javax.swing.JLabel();
        Blocks5 = new javax.swing.JLabel();
        Blocks6 = new javax.swing.JLabel();
        Blocks7 = new javax.swing.JLabel();
        Blocks8 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        Blocks10 = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        Blocks9 = new javax.swing.JLabel();
        Blocks11 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Screen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Screen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Man.setBackground(new java.awt.Color(255, 51, 51));
        Man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mario_game/mario_right.gif"))); // NOI18N
        Man.setFocusable(false);
        Man.setName(""); // NOI18N
        Screen.add(Man, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 20, 30));

        Ground.setBackground(new java.awt.Color(0, 204, 0));
        Ground.setFocusable(false);
        Ground.setName("ground"); // NOI18N
        Ground.setOpaque(true);
        Screen.add(Ground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 600, 90));

        Blocks.setBackground(new java.awt.Color(153, 51, 0));
        Blocks.setFocusable(false);
        Blocks.setName("ground"); // NOI18N
        Blocks.setOpaque(true);
        Screen.add(Blocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, 40));

        Blocks4.setBackground(new java.awt.Color(153, 51, 0));
        Blocks4.setFocusable(false);
        Blocks4.setName("ground"); // NOI18N
        Blocks4.setOpaque(true);
        Screen.add(Blocks4, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 340, 30, 40));

        Blocks1.setBackground(new java.awt.Color(153, 51, 0));
        Blocks1.setFocusable(false);
        Blocks1.setName("ground"); // NOI18N
        Blocks1.setOpaque(true);
        Screen.add(Blocks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 100, 20));

        Blocks3.setBackground(new java.awt.Color(153, 51, 0));
        Blocks3.setFocusable(false);
        Blocks3.setName("ground"); // NOI18N
        Blocks3.setOpaque(true);
        Screen.add(Blocks3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 100, 21));

        Blocks5.setBackground(new java.awt.Color(153, 51, 0));
        Blocks5.setFocusable(false);
        Blocks5.setName("ground"); // NOI18N
        Blocks5.setOpaque(true);
        Screen.add(Blocks5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 80, 30));

        Blocks6.setBackground(new java.awt.Color(153, 51, 0));
        Blocks6.setFocusable(false);
        Blocks6.setName("ground"); // NOI18N
        Blocks6.setOpaque(true);
        Screen.add(Blocks6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 30, 40));

        Blocks7.setBackground(new java.awt.Color(153, 51, 0));
        Blocks7.setFocusable(false);
        Blocks7.setName("ground"); // NOI18N
        Blocks7.setOpaque(true);
        Screen.add(Blocks7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 5, 50));

        Blocks8.setBackground(new java.awt.Color(153, 51, 0));
        Blocks8.setFocusable(false);
        Blocks8.setName("ground"); // NOI18N
        Blocks8.setOpaque(true);
        Screen.add(Blocks8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 100, 20));

        info.setBackground(new java.awt.Color(153, 51, 0));
        info.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setFocusable(false);
        info.setName("ground"); // NOI18N
        info.setOpaque(true);
        Screen.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, 20));

        Blocks10.setBackground(new java.awt.Color(153, 51, 0));
        Blocks10.setFocusable(false);
        Blocks10.setName("ground"); // NOI18N
        Blocks10.setOpaque(true);
        Screen.add(Blocks10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 30, 40));

        info1.setBackground(new java.awt.Color(153, 51, 0));
        info1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        info1.setForeground(new java.awt.Color(255, 255, 255));
        info1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info1.setFocusable(false);
        info1.setName("ground"); // NOI18N
        info1.setOpaque(true);
        Screen.add(info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 20));

        info2.setBackground(new java.awt.Color(153, 51, 0));
        info2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        info2.setForeground(new java.awt.Color(255, 255, 255));
        info2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info2.setFocusable(false);
        info2.setName("ground"); // NOI18N
        info2.setOpaque(true);
        Screen.add(info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 100, 20));

        info3.setBackground(new java.awt.Color(153, 51, 0));
        info3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        info3.setForeground(new java.awt.Color(255, 255, 255));
        info3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info3.setFocusable(false);
        info3.setName("ground"); // NOI18N
        info3.setOpaque(true);
        Screen.add(info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, 30));

        Blocks9.setBackground(new java.awt.Color(153, 51, 0));
        Blocks9.setFocusable(false);
        Blocks9.setName("ground"); // NOI18N
        Blocks9.setOpaque(true);
        Screen.add(Blocks9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 30, 20));

        Blocks11.setBackground(new java.awt.Color(153, 51, 0));
        Blocks11.setFocusable(false);
        Blocks11.setName("ground"); // NOI18N
        Blocks11.setOpaque(true);
        Screen.add(Blocks11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 100, 20));

        BG.setBackground(new java.awt.Color(153, 204, 255));
        BG.setFocusTraversalPolicyProvider(true);
        BG.setFocusable(false);
        BG.setName("BG"); // NOI18N
        BG.setOpaque(true);
        BG.setPreferredSize(new Dimension(Screen.getWidth(),Screen.getHeight()));
        Screen.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        getContentPane().add(Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean left,right,jump=false;
int x_velocity=5,y_velocity=0;
final float jump_acc=10;
final int gravity=1;
int man_width,man_height;

boolean onGround(){
Rectangle r1 = Man.getBounds();
Rectangle r2 = null;
r1.setLocation(r1.x,r1.y+1);
Component ground = Screen.getComponentAt(r1.x+r1.width-1,r1.y+r1.height);
if(!(ground.getName().equals("ground")))
ground = Screen.getComponentAt(r1.x,r1.y+r1.height);    
if(ground.getName().equals("ground"))
r2= ground.getBounds();
else
return false;
Rectangle overlap = r1.intersection(r2);
if(overlap.width>=5){
return true;
}
else
return false;
}
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_LEFT)
    left=true;
if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
    right=true;    
if((evt.getKeyCode()==KeyEvent.VK_UP)&&(onGround())){
    jump=true; 
}
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
if(evt.getKeyCode()==KeyEvent.VK_LEFT)
    left=false;
if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
    right=false;    
// TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
requestFocus();  
man_width = Man.getWidth();
man_height=Man.getHeight();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Platform_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Platform_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Platform_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platform_Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Platform_Game().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Blocks;
    private javax.swing.JLabel Blocks1;
    private javax.swing.JLabel Blocks10;
    private javax.swing.JLabel Blocks11;
    private javax.swing.JLabel Blocks3;
    private javax.swing.JLabel Blocks4;
    private javax.swing.JLabel Blocks5;
    private javax.swing.JLabel Blocks6;
    private javax.swing.JLabel Blocks7;
    private javax.swing.JLabel Blocks8;
    private javax.swing.JLabel Blocks9;
    private javax.swing.JLabel Ground;
    private javax.swing.JLabel Man;
    private javax.swing.JPanel Screen;
    private javax.swing.JLabel info;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel info3;
    // End of variables declaration//GEN-END:variables
}
