/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Bouncing_Icons.java
 *
 * Created on Apr 5, 2012, 1:21:35 PM
 */

package Simple_Programs;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author student
 */
@SuppressWarnings("serial")
public class Bouncing_Icons extends javax.swing.JFrame {

    /** Creates new form Bouncing_Icons */
    public Bouncing_Icons() {
        initComponents();
             t = new Timer(10,
           new ActionListener(){
           public void actionPerformed(ActionEvent e){
            
            if(bounce1==true)
            icon_bounce(icon1);
            else
            fall(icon1);
                        
            if(bounce2==true)
            icon_bounce(icon2);
            else
            fall(icon2);
            
            if(bounce3==true)
            icon_bounce(icon3);
            else
            fall(icon3);
            
            if(bounce4==true)
            icon_bounce(icon4);
            else
            fall(icon4);
            
            if(bounce5==true)
            icon_bounce(icon5);
            else
            fall(icon5);
            
            if(bounce6==true)
            icon_bounce(icon6);
            else
            fall(icon6);

           }
        });
        t.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        icon5 = new javax.swing.JLabel();
        icon6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/icon1.png"))); // NOI18N
        icon1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon1MouseExited(evt);
            }
        });
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 71, 150));

        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/icon2.png"))); // NOI18N
        icon2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon2MouseExited(evt);
            }
        });
        getContentPane().add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 71, 150));

        icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/icon4.png"))); // NOI18N
        icon3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon3MouseExited(evt);
            }
        });
        getContentPane().add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 150));

        icon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/icon3.png"))); // NOI18N
        icon4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon4MouseExited(evt);
            }
        });
        getContentPane().add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 71, 150));

        icon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/icon6.png"))); // NOI18N
        icon5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon5MouseExited(evt);
            }
        });
        getContentPane().add(icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 71, 150));

        icon6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/icon5.png"))); // NOI18N
        icon6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        icon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon6MouseExited(evt);
            }
        });
        getContentPane().add(icon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 71, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void icon_bounce(Component c)
{
int x=c.getX(),y=c.getY();

if(y==270)
up=false;
if(y==300)
up=true;
if(up==true)
c.setLocation(x,y-2);
if(up==false)
c.setLocation(x,y+2);
}
void fall(Component c)
{
int x=c.getX(),y=c.getY();
if(y<300)
c.setLocation(x,y+2);
}

boolean up = true;
boolean bounce1 = false;
boolean bounce2 = false;
boolean bounce3 = false;
boolean bounce4 = false;
boolean bounce5 = false;
boolean bounce6 = false;

Timer t;
    private void icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseEntered
bounce1=true;

    }//GEN-LAST:event_icon1MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void icon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseExited
bounce1=false;
    }//GEN-LAST:event_icon1MouseExited

    private void icon2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseEntered
bounce2=true;
    }//GEN-LAST:event_icon2MouseEntered

    private void icon2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseExited
bounce2=false;
    }//GEN-LAST:event_icon2MouseExited

    private void icon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseEntered
bounce3=true;
    }//GEN-LAST:event_icon3MouseEntered

    private void icon3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseExited
bounce3=false;
    }//GEN-LAST:event_icon3MouseExited

    private void icon4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseEntered
bounce4=true;
    }//GEN-LAST:event_icon4MouseEntered

    private void icon4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseExited
bounce4=false;
    }//GEN-LAST:event_icon4MouseExited

    private void icon5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon5MouseEntered
bounce5=true;
    }//GEN-LAST:event_icon5MouseEntered

    private void icon5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon5MouseExited
bounce5=false;
    }//GEN-LAST:event_icon5MouseExited

    private void icon6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon6MouseEntered
bounce6=true;
    }//GEN-LAST:event_icon6MouseEntered

    private void icon6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon6MouseExited
bounce6=false;
    }//GEN-LAST:event_icon6MouseExited

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bouncing_Icons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    // End of variables declaration//GEN-END:variables

}
