/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Conector_Dots.java
 *
 * Created on Jul 11, 2012, 9:31:49 PM
 */
package Simple_Programs;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;

/**
 *
 * @author aki
 */
public class Conector_Dots extends javax.swing.JFrame {

    /** Creates new form Conector_Dots */
    public Conector_Dots() {
        initComponents();
    
        
        //Set up the drawing area.
       board.setViewportView(drawpanel);

       
       drawpanel.repaint();
       drawpanel.setAutoscrolls(true); //allows dragging?
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dot1 = new javax.swing.JLabel();
        dot2 = new javax.swing.JLabel();
        dot3 = new javax.swing.JLabel();
        dot4 = new javax.swing.JLabel();
        dot5 = new javax.swing.JLabel();
        dot6 = new javax.swing.JLabel();
        dot7 = new javax.swing.JLabel();
        dot8 = new javax.swing.JLabel();
        dot9 = new javax.swing.JLabel();
        empty = new javax.swing.JLabel();
        board = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dot1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 50));

        dot2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 50));

        dot3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 50));

        dot4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 50, 50));

        dot5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, 50));

        dot6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 50, 50));

        dot7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 50, 50));

        dot8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 50));

        dot9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mobile_Operating_System/red_connector_dot.png"))); // NOI18N
        dot9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Selected(evt);
            }
        });
        dot9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawondot(evt);
            }
        });
        getContentPane().add(dot9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 50, 50));

        empty.setBackground(new java.awt.Color(0, 0, 0));
        empty.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                emptyMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                emptyMouseMoved(evt);
            }
        });
        getContentPane().add(empty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));
        getContentPane().add(board, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        ta.setColumns(20);
        ta.setEditable(false);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 350, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

Point mp;
Point p1,p2,p3,p4,p5,p6,p7,p8,p9;
int xp[]={0,0,0,0,0,0,0,0,0,0};
int yp[]={0,0,0,0,0,0,0,0,0,0};
int dot=0;
//End of Variables
boolean mouseondot(Point p)
{
Point mp = getMousePosition();
mp.x-=4;mp.y-=30;
mp.x=mp.x-(mp.x%50);
mp.y=mp.y-(mp.y%50);
if((mp.x==p.x)&&(mp.y==p.y))
return true;
else
return false;
}

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
p1=dot1.getLocation();p2=dot2.getLocation();p3=dot3.getLocation();
p4=dot4.getLocation();p5=dot5.getLocation();p6=dot6.getLocation();
p7=dot7.getLocation();p8=dot8.getLocation();p9=dot9.getLocation();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void emptyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyMouseMoved
if((dot<9)&&(dot>0)){
mp = getMousePosition();
mp.x-=4;
mp.y-=30;
xp[dot]=mp.x;
yp[dot]=mp.y;
repaint();
}
ta.setText(mp.x+","+mp.y+"\n Dot="+dot);
// TODO add your handling code here:
    }//GEN-LAST:event_emptyMouseMoved

    private void emptyMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptyMouseDragged

    }//GEN-LAST:event_emptyMouseDragged

    private void Selected(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Selected
boolean connected=true;
mp = getMousePosition();
mp.x-=4;
mp.y-=30;
xp[dot]=mp.x-(mp.x%50)+23;
yp[dot]=mp.y-(mp.y%50)+22;
xp[dot+1]=mp.x-(mp.x%50)+23;
yp[dot+1]=mp.y-(mp.y%50)+22;
repaint();
dot++;
    }//GEN-LAST:event_Selected

    private void drawondot(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawondot
if((dot<9)&&(dot>0)){
mp = getMousePosition();
mp.x-=4;
mp.y-=30;
xp[dot]=mp.x;
yp[dot]=mp.y;
repaint();
}
ta.setText(mp.x+","+mp.y+"\n Dot="+dot);
    }//GEN-LAST:event_drawondot
  public final class InnerClassDrawingPanel extends javax.swing.JPanel {    
        @Override
        protected void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D)g;
        super.paintComponent(g2d);
        g2d.clearRect(0, 0,empty.getX(),empty.getY());
        g2d.setColor(new Color(255,100,100));
        g2d.setStroke(new BasicStroke(15f,BasicStroke.CAP_ROUND,BasicStroke.JOIN_ROUND));
        g2d.drawPolyline(xp,yp,dot+1);
        g2d.clearRect(0, 0,10,10);
        drawpanel.setAutoscrolls(true); 
          }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conector_Dots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conector_Dots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conector_Dots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conector_Dots.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Conector_Dots().setVisible(true);
            }
        });
    }
    private InnerClassDrawingPanel drawpanel = new InnerClassDrawingPanel();;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane board;
    private javax.swing.JLabel dot1;
    private javax.swing.JLabel dot2;
    private javax.swing.JLabel dot3;
    private javax.swing.JLabel dot4;
    private javax.swing.JLabel dot5;
    private javax.swing.JLabel dot6;
    private javax.swing.JLabel dot7;
    private javax.swing.JLabel dot8;
    private javax.swing.JLabel dot9;
    private javax.swing.JLabel empty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
