/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Man_Moving.java
 *
 * Created on May 19, 2012, 1:52:25 AM
 */
package Simple_Programs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author $Akshay$
 */
@SuppressWarnings("serial")
public class Man_Moving extends javax.swing.JFrame {

    /** Creates new form Man_Moving */
    public Man_Moving() {
        initComponents();
        Timer move = new Timer(25,new ActionListener(){
            public void actionPerformed(ActionEvent e){
               if(right==true){
                   x+=n;
                   o.setIcon(new ImageIcon(getClass().getResource("/other_Program_Images/walking_right.gif")));
               }
               if(left==true){
                   x-=n;
                   o.setIcon(new ImageIcon(getClass().getResource("/other_Program_Images/walking_left.gif")));
               }
               if(down==true){
                   y+=n;
                   o.setIcon(new ImageIcon(getClass().getResource("/other_Program_Images/walking_forward.gif")));
               }
               if(up==true){
                  y-=n;
                  o.setIcon(new ImageIcon(getClass().getResource("/other_Program_Images/walking_backwards.gif")));
               }
  
               o.setLocation(x,y);
            
               
            }});
        move.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        o.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        o.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/walking_forward.gif"))); // NOI18N
        o.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        o.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oKeyPressed(evt);
            }
        });
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 50, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/map.jpg"))); // NOI18N
        jLabel1.setText("©$Dollar Akshay$");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean right, left, down, up;
public int x=100,y=100;
int n=3;
    private void oKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oKeyPressed

  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_oKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
if (evt.getKeyCode() == 37){
left = true;
}
if (evt.getKeyCode() == 39){
right = true;
}
if (evt.getKeyCode() == 38){
up = true;
}
if (evt.getKeyCode() == 40){
down = true;
}

        
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
		if (evt.getKeyCode() == 37){
		left = false;
		}
		if (evt.getKeyCode() == 39){
		right = false;
		}
		if (evt.getKeyCode() == 38){
		up = false;
		}
		if (evt.getKeyCode() == 40){
		down = false;
		}
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Man_Moving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Man_Moving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Man_Moving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Man_Moving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Man_Moving().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel o;
    // End of variables declaration//GEN-END:variables
}
