/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Simple_Programs;

/**
 *
 * @author $Akshay$
 */
public class Mousehunt_CatchRate extends javax.swing.JFrame {

  /**
   * Creates new form Mousehunt_CatchRate
   */
  public Mousehunt_CatchRate() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    Pow = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    Eff = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    Luck = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    Mouse = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    ta = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
    jLabel1.setText("Trap Power");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 39, 193, 56));

    Pow.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
    Pow.setText("0");
    getContentPane().add(Pow, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 38, 159, 56));

    jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
    jLabel2.setText("Effectiveness");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 102, 193, 56));

    Eff.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
    Eff.setText("0");
    getContentPane().add(Eff, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 101, 159, 56));

    jLabel3.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
    jLabel3.setText("Luck");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 165, 193, 56));

    Luck.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
    Luck.setText("0");
    getContentPane().add(Luck, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 164, 159, 56));

    jLabel4.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
    jLabel4.setText("Mouse Power");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 233, 193, 56));

    Mouse.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
    Mouse.setText("0");
    getContentPane().add(Mouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 232, 159, 56));

    ta.setColumns(20);
    ta.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    ta.setRows(5);
    jScrollPane1.setViewportView(ta);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, 525, 158));

    jButton1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
    jButton1.setText("Calculate");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 108, 162, 57));

    jLabel5.setText("jLabel5");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
float pow = Float.parseFloat(Pow.getText());
float eff = Float.parseFloat(Eff.getText()); 
eff/=100;
float luck = Float.parseFloat(Luck.getText());
float mouse = Float.parseFloat(Mouse.getText());

float r = (eff*pow + (3-eff)*(eff*luck)*(eff*luck))/(eff*pow + mouse);
r*=100;
ta.setText(""+r+" %");

  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Mousehunt_CatchRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Mousehunt_CatchRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Mousehunt_CatchRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Mousehunt_CatchRate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Mousehunt_CatchRate().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField Eff;
  private javax.swing.JTextField Luck;
  private javax.swing.JTextField Mouse;
  private javax.swing.JTextField Pow;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea ta;
  // End of variables declaration//GEN-END:variables
}
