/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rainbow.java
 *
 * Created on Aug 7, 2011, 6:19:25 PM
 */

package Simple_Programs;

import java.awt.Color;
import java.awt.Point;

/**
 *
 * @author Akshay
 */
public class Rainbow extends javax.swing.JFrame {

    /** Creates new form Rainbow */
    public Rainbow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clr = new javax.swing.JButton();
        me = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        box = new javax.swing.JPanel();
        rd = new java.awt.Canvas();
        o = new java.awt.Canvas();
        y = new java.awt.Canvas();
        g = new java.awt.Canvas();
        b = new java.awt.Canvas();
        i = new java.awt.Canvas();
        v = new java.awt.Canvas();
        jButton2 = new javax.swing.JButton();
        Copyrights = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clr.setFont(new java.awt.Font("Tahoma", 1, 18));
        clr.setText("All White");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });

        me.setFont(new java.awt.Font("Tahoma", 1, 18));
        me.setText("Color One");
        me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("Color All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        box.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        box.setLayout(new java.awt.GridLayout(1, 0));

        rd.setBackground(new java.awt.Color(255, 255, 255));
        rd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdMouseExited(evt);
            }
        });
        rd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rdMouseMoved(evt);
            }
        });
        box.add(rd);

        o.setBackground(new java.awt.Color(255, 255, 255));
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oMouseExited(evt);
            }
        });
        o.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oMouseMoved(evt);
            }
        });
        box.add(o);

        y.setBackground(new java.awt.Color(255, 255, 255));
        y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yMouseExited(evt);
            }
        });
        y.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                yMouseMoved(evt);
            }
        });
        box.add(y);

        g.setBackground(new java.awt.Color(255, 255, 255));
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gMouseExited(evt);
            }
        });
        g.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gMouseMoved(evt);
            }
        });
        box.add(g);

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
        });
        b.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bMouseMoved(evt);
            }
        });
        box.add(b);

        i.setBackground(new java.awt.Color(255, 255, 255));
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iMouseExited(evt);
            }
        });
        i.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iMouseMoved(evt);
            }
        });
        box.add(i);

        v.setBackground(new java.awt.Color(255, 255, 255));
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vMouseExited(evt);
            }
        });
        v.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                vMouseMoved(evt);
            }
        });
        box.add(v);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton2.setText("Reverse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Copyrights.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        Copyrights.setText("© $Dollar Akshay$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(me, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(Copyrights))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(clr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Copyrights))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int k=0;
int r=0;
private void rdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMouseMoved
if(r==0)
rd.setBackground(Color.RED);
else if(r==1)
rd.setBackground(new Color(114,0,153));

// TODO add your handling code here:
}//GEN-LAST:event_rdMouseMoved

    private void oMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseMoved
if(r==0)
o.setBackground(Color.ORANGE);
else if(r==1)
o.setBackground(new Color(0,0,153));

// TODO add your handling code here:
}//GEN-LAST:event_oMouseMoved

    private void yMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMouseMoved
if(r==0)
y.setBackground(Color.YELLOW);
else if(r==1)
y.setBackground(Color.BLUE);

// TODO add your handling code here:
}//GEN-LAST:event_yMouseMoved

    private void gMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseMoved
g.setBackground(Color.GREEN);
// TODO add your handling code here:
}//GEN-LAST:event_gMouseMoved

    private void bMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseMoved
if(r==1)
b.setBackground(Color.YELLOW);
else if(r==0)
b.setBackground(Color.BLUE);
// TODO add your handling code here:
}//GEN-LAST:event_bMouseMoved

    private void iMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseMoved
if(r==1)
i.setBackground(Color.ORANGE);
else if(r==0)
i.setBackground(new Color(0,0,153));
        // TODO add your handling code here:
}//GEN-LAST:event_iMouseMoved

    private void vMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseMoved
if(r==1)
v.setBackground(Color.RED);
else if(r==0)
v.setBackground(new Color(114,0,153));

        // TODO add your handling code here:
}//GEN-LAST:event_vMouseMoved

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed


v.setBackground(new Color(255,255,255));
i.setBackground(new Color(255,255,255));
g.setBackground(new Color(255,255,255));
b.setBackground(new Color(255,255,255));
y.setBackground(new Color(255,255,255));
o.setBackground(new Color(255,255,255));
rd.setBackground(new Color(255,255,255));


// TODO add your handling code here:
}//GEN-LAST:event_clrActionPerformed

    private void meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meActionPerformed
k=1;
        // TODO add your handling code here:
}//GEN-LAST:event_meActionPerformed

    private void rdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMouseExited
if(k==1)
rd.setBackground(new Color(255,255,255));

        // TODO add your handling code here:
}//GEN-LAST:event_rdMouseExited

    private void oMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseExited
if(k==1)
o.setBackground(new Color(255,255,255));
// TODO add your handling code here:
    }//GEN-LAST:event_oMouseExited

    private void yMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMouseExited
if(k==1)
y.setBackground(new Color(255,255,255));
// TODO add your handling code here:
    }//GEN-LAST:event_yMouseExited

    private void gMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseExited
if(k==1)
g.setBackground(new Color(255,255,255));

// TODO add your handling code here:
    }//GEN-LAST:event_gMouseExited

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited
if(k==1)
b.setBackground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_bMouseExited

    private void iMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseExited
if(k==1)
i.setBackground(new Color(255,255,255));
// TODO add your handling code here:
    }//GEN-LAST:event_iMouseExited

    private void vMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseExited
if(k==1)
v.setBackground(new Color(255,255,255));
// TODO add your handling code here:
    }//GEN-LAST:event_vMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        k=0;

        // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
r++;
r=r%2;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rainbow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copyrights;
    private java.awt.Canvas b;
    private javax.swing.JPanel box;
    private javax.swing.JButton clr;
    private java.awt.Canvas g;
    private java.awt.Canvas i;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton me;
    private java.awt.Canvas o;
    private java.awt.Canvas rd;
    private java.awt.Canvas v;
    private java.awt.Canvas y;
    // End of variables declaration//GEN-END:variables

}
