/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Shut_Your_Window.java
 *
 * Created on Aug 7, 2011, 7:22:01 PM
 */

package Simple_Programs;

import java.awt.Color;

/**
 *
 * @author Akshay
 */
public class Shut_Your_Window extends javax.swing.JFrame {

    /** Creates new form Shut_Your_Window */
    public Shut_Your_Window() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Copyrights = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rd = new java.awt.Canvas();
        o = new java.awt.Canvas();
        y = new java.awt.Canvas();
        g = new java.awt.Canvas();
        b = new java.awt.Canvas();
        i = new java.awt.Canvas();
        v = new java.awt.Canvas();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        window = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Copyrights.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        Copyrights.setText("© $Dollar Akshay$");
        getContentPane().add(Copyrights, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        rd.setBackground(new java.awt.Color(255, 255, 255));
        rd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdMouseExited(evt);
            }
        });
        rd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rdMouseMoved(evt);
            }
        });
        jPanel1.add(rd);

        o.setBackground(new java.awt.Color(255, 255, 255));
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oMouseExited(evt);
            }
        });
        o.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                oMouseMoved(evt);
            }
        });
        jPanel1.add(o);

        y.setBackground(new java.awt.Color(255, 255, 255));
        y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yMouseExited(evt);
            }
        });
        y.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                yMouseMoved(evt);
            }
        });
        jPanel1.add(y);

        g.setBackground(new java.awt.Color(255, 255, 255));
        g.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gMouseExited(evt);
            }
        });
        g.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gMouseMoved(evt);
            }
        });
        jPanel1.add(g);

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bMouseExited(evt);
            }
        });
        b.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bMouseMoved(evt);
            }
        });
        jPanel1.add(b);

        i.setBackground(new java.awt.Color(255, 255, 255));
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iMouseExited(evt);
            }
        });
        i.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iMouseMoved(evt);
            }
        });
        jPanel1.add(i);

        v.setBackground(new java.awt.Color(255, 255, 255));
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vMouseExited(evt);
            }
        });
        v.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                vMouseMoved(evt);
            }
        });
        jPanel1.add(v);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, 240));

        canvas1.setBackground(new java.awt.Color(255, 255, 204));
        canvas1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvas1MouseMoved(evt);
            }
        });
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 150, 380));

        canvas2.setBackground(new java.awt.Color(255, 255, 204));
        canvas2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvas2MouseMoved(evt);
            }
        });
        getContentPane().add(canvas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 380));

        window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Window.JPG"))); // NOI18N
        getContentPane().add(window, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1, -1, 141));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canvas2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas2MouseMoved
        r=1;
        // TODO add your handling code here:
}//GEN-LAST:event_canvas2MouseMoved

    private void canvas1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseMoved
        r=0;
        // TODO add your handling code here:
}//GEN-LAST:event_canvas1MouseMoved

    private void vMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseMoved
        if(r==1)
            v.setBackground(Color.RED);
        else if(r==0)
            v.setBackground(new Color(114,0,153));

        // TODO add your handling code here:
}//GEN-LAST:event_vMouseMoved

    private void vMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseExited
        if(k==1)
            v.setBackground(new Color(255,255,255));
        // TODO add your handling code here:
}//GEN-LAST:event_vMouseExited

    private void iMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseMoved
        if(r==1)
            i.setBackground(Color.ORANGE);
        else if(r==0)
            i.setBackground(new Color(0,0,153));
        // TODO add your handling code here:
}//GEN-LAST:event_iMouseMoved

    private void iMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseExited
        if(k==1)
            i.setBackground(new Color(255,255,255));
        // TODO add your handling code here:
}//GEN-LAST:event_iMouseExited

    private void bMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseMoved
        if(r==1)
            b.setBackground(Color.YELLOW);
        else if(r==0)
            b.setBackground(Color.BLUE);
        // TODO add your handling code here:
}//GEN-LAST:event_bMouseMoved

    private void bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseExited
        if(k==1)
            b.setBackground(new Color(255,255,255));
        // TODO add your handling code here:
}//GEN-LAST:event_bMouseExited

    private void gMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseMoved
        g.setBackground(Color.GREEN);
        // TODO add your handling code here:
}//GEN-LAST:event_gMouseMoved

    private void gMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseExited
        if(k==1)
            g.setBackground(new Color(255,255,255));

        // TODO add your handling code here:
}//GEN-LAST:event_gMouseExited

    private void yMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMouseMoved
        if(r==0)
            y.setBackground(Color.YELLOW);
        else if(r==1)
            y.setBackground(Color.BLUE);

        // TODO add your handling code here:
}//GEN-LAST:event_yMouseMoved

    private void yMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMouseExited
        if(k==1)
            y.setBackground(new Color(255,255,255));
        // TODO add your handling code here:
}//GEN-LAST:event_yMouseExited

    private void oMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseMoved
        if(r==0)
            o.setBackground(Color.ORANGE);
        else if(r==1)
            o.setBackground(new Color(0,0,153));

        // TODO add your handling code here:
}//GEN-LAST:event_oMouseMoved

    private void oMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseExited
        if(k==1)
            o.setBackground(new Color(255,255,255));
        // TODO add your handling code here:
}//GEN-LAST:event_oMouseExited

    private void rdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMouseMoved
        if(r==0)
            rd.setBackground(Color.RED);
        else if(r==1)
            rd.setBackground(new Color(114,0,153));

        // TODO add your handling code here:
}//GEN-LAST:event_rdMouseMoved

    private void rdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMouseExited
        if(k==1)
            rd.setBackground(new Color(255,255,255));

        // TODO add your handling code here:
}//GEN-LAST:event_rdMouseExited
int r=0,k=0;
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shut_Your_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copyrights;
    private java.awt.Canvas b;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private java.awt.Canvas g;
    private java.awt.Canvas i;
    private javax.swing.JPanel jPanel1;
    private java.awt.Canvas o;
    private java.awt.Canvas rd;
    private java.awt.Canvas v;
    private javax.swing.JLabel window;
    private java.awt.Canvas y;
    // End of variables declaration//GEN-END:variables

}
