/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sinusoidal_wave.java
 *
 * Created on Nov 23, 2011, 11:01:46 AM
 */

package Simple_Programs;


import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author student
 */
public class Sinusoidal_wave extends javax.swing.JFrame {

    /** Creates new form Sinusoidal_wave */
    public Sinusoidal_wave() {
        initComponents();
        timer = new Timer(10,new ActionListener(){
            public void actionPerformed(ActionEvent e){
             t+=0.01;
setPosition(circle01,1);setPosition(circle02,2);setPosition(circle03,3);setPosition(circle04,4);setPosition(circle05,5);setPosition(circle06,6);setPosition(circle07,7);setPosition(circle08,8);setPosition(circle09,9);setPosition(circle10,10);
setPosition(circle11,11);setPosition(circle12,12);setPosition(circle13,13);setPosition(circle14,14);setPosition(circle15,15);setPosition(circle16,16);setPosition(circle17,17);setPosition(circle18,18);setPosition(circle19,19);setPosition(circle20,20);
setPosition(circle21,21);setPosition(circle22,22);setPosition(circle23,23);setPosition(circle24,24);setPosition(circle25,25);setPosition(circle26,26);setPosition(circle27,27);setPosition(circle28,28);setPosition(circle29,29);setPosition(circle30,30);
setPosition(circle31,31);setPosition(circle32,32);setPosition(circle33,33);setPosition(circle34,34);setPosition(circle35,35);setPosition(circle36,36);setPosition(circle37,37);setPosition(circle38,38);setPosition(circle39,39);setPosition(circle40,40);
setPosition(circle41,41);setPosition(circle42,42);setPosition(circle43,43);setPosition(circle44,44);setPosition(circle45,45);setPosition(circle46,46);setPosition(circle47,47);setPosition(circle48,48);setPosition(circle49,49);setPosition(circle50,50);
setPosition(circle51,51);setPosition(circle52,52);setPosition(circle53,53);setPosition(circle54,54);setPosition(circle55,55);setPosition(circle56,56);setPosition(circle57,57);setPosition(circle58,58);setPosition(circle59,59);setPosition(circle60,60);
setPosition(circle61,61);setPosition(circle62,62);setPosition(circle63,63);setPosition(circle64,64);setPosition(circle65,65);setPosition(circle66,66);setPosition(circle67,67);setPosition(circle68,68);setPosition(circle69,69);setPosition(circle70,70);
setPosition(circle71,71);setPosition(circle72,72);setPosition(circle73,73);setPosition(circle74,74);setPosition(circle75,75);setPosition(circle76,76);setPosition(circle77,77);setPosition(circle78,78);setPosition(circle79,79);setPosition(circle80,80);
setPosition(circle81,81);setPosition(circle82,82);setPosition(circle83,83);setPosition(circle84,84);setPosition(circle85,85);setPosition(circle86,86);setPosition(circle87,87);setPosition(circle88,88);setPosition(circle89,89);setPosition(circle90,90);
setPosition(circle91,91);setPosition(circle92,92);setPosition(circle93,93);setPosition(circle94,94);setPosition(circle95,95);setPosition(circle96,96);setPosition(circle97,97);setPosition(circle98,98);setPosition(circle99,99);setPosition(circle100,100);
    
            }
        });
        timer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        circle01 = new javax.swing.JLabel();
        circle02 = new javax.swing.JLabel();
        circle03 = new javax.swing.JLabel();
        circle04 = new javax.swing.JLabel();
        circle05 = new javax.swing.JLabel();
        circle06 = new javax.swing.JLabel();
        circle07 = new javax.swing.JLabel();
        circle08 = new javax.swing.JLabel();
        circle09 = new javax.swing.JLabel();
        circle10 = new javax.swing.JLabel();
        circle11 = new javax.swing.JLabel();
        circle12 = new javax.swing.JLabel();
        circle13 = new javax.swing.JLabel();
        circle14 = new javax.swing.JLabel();
        circle15 = new javax.swing.JLabel();
        circle16 = new javax.swing.JLabel();
        circle17 = new javax.swing.JLabel();
        circle18 = new javax.swing.JLabel();
        circle19 = new javax.swing.JLabel();
        circle20 = new javax.swing.JLabel();
        circle21 = new javax.swing.JLabel();
        circle22 = new javax.swing.JLabel();
        circle23 = new javax.swing.JLabel();
        circle24 = new javax.swing.JLabel();
        circle25 = new javax.swing.JLabel();
        circle26 = new javax.swing.JLabel();
        circle27 = new javax.swing.JLabel();
        circle28 = new javax.swing.JLabel();
        circle29 = new javax.swing.JLabel();
        circle30 = new javax.swing.JLabel();
        circle31 = new javax.swing.JLabel();
        circle32 = new javax.swing.JLabel();
        circle33 = new javax.swing.JLabel();
        circle34 = new javax.swing.JLabel();
        circle35 = new javax.swing.JLabel();
        circle36 = new javax.swing.JLabel();
        circle37 = new javax.swing.JLabel();
        circle38 = new javax.swing.JLabel();
        circle39 = new javax.swing.JLabel();
        circle40 = new javax.swing.JLabel();
        circle41 = new javax.swing.JLabel();
        circle42 = new javax.swing.JLabel();
        circle43 = new javax.swing.JLabel();
        circle44 = new javax.swing.JLabel();
        circle45 = new javax.swing.JLabel();
        circle46 = new javax.swing.JLabel();
        circle47 = new javax.swing.JLabel();
        circle48 = new javax.swing.JLabel();
        circle49 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        amp = new javax.swing.JRadioButton();
        face = new javax.swing.JRadioButton();
        lam = new javax.swing.JRadioButton();
        omg = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        circle50 = new javax.swing.JLabel();
        circle51 = new javax.swing.JLabel();
        circle52 = new javax.swing.JLabel();
        circle53 = new javax.swing.JLabel();
        circle54 = new javax.swing.JLabel();
        circle55 = new javax.swing.JLabel();
        circle56 = new javax.swing.JLabel();
        circle57 = new javax.swing.JLabel();
        circle58 = new javax.swing.JLabel();
        circle59 = new javax.swing.JLabel();
        circle60 = new javax.swing.JLabel();
        circle61 = new javax.swing.JLabel();
        circle62 = new javax.swing.JLabel();
        circle63 = new javax.swing.JLabel();
        circle64 = new javax.swing.JLabel();
        circle65 = new javax.swing.JLabel();
        circle66 = new javax.swing.JLabel();
        circle67 = new javax.swing.JLabel();
        circle68 = new javax.swing.JLabel();
        circle69 = new javax.swing.JLabel();
        circle70 = new javax.swing.JLabel();
        circle71 = new javax.swing.JLabel();
        circle72 = new javax.swing.JLabel();
        circle73 = new javax.swing.JLabel();
        circle74 = new javax.swing.JLabel();
        circle75 = new javax.swing.JLabel();
        circle76 = new javax.swing.JLabel();
        circle77 = new javax.swing.JLabel();
        circle78 = new javax.swing.JLabel();
        circle79 = new javax.swing.JLabel();
        circle80 = new javax.swing.JLabel();
        circle81 = new javax.swing.JLabel();
        circle82 = new javax.swing.JLabel();
        circle83 = new javax.swing.JLabel();
        circle84 = new javax.swing.JLabel();
        circle85 = new javax.swing.JLabel();
        circle86 = new javax.swing.JLabel();
        circle87 = new javax.swing.JLabel();
        circle88 = new javax.swing.JLabel();
        circle89 = new javax.swing.JLabel();
        circle90 = new javax.swing.JLabel();
        circle91 = new javax.swing.JLabel();
        circle92 = new javax.swing.JLabel();
        circle93 = new javax.swing.JLabel();
        circle94 = new javax.swing.JLabel();
        circle95 = new javax.swing.JLabel();
        circle96 = new javax.swing.JLabel();
        circle97 = new javax.swing.JLabel();
        circle98 = new javax.swing.JLabel();
        circle99 = new javax.swing.JLabel();
        circle100 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, -1, -1));

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        getContentPane().add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 100, -1));

        circle01.setBackground(new java.awt.Color(0, 0, 0));
        circle01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle02.setBackground(new java.awt.Color(0, 0, 0));
        circle02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle03.setBackground(new java.awt.Color(0, 0, 0));
        circle03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle04.setBackground(new java.awt.Color(0, 0, 0));
        circle04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle04, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle05.setBackground(new java.awt.Color(0, 0, 0));
        circle05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle05, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle06.setBackground(new java.awt.Color(0, 0, 0));
        circle06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle06, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle07.setBackground(new java.awt.Color(0, 0, 0));
        circle07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle07, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle08.setBackground(new java.awt.Color(0, 0, 0));
        circle08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle08, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle09.setBackground(new java.awt.Color(0, 0, 0));
        circle09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle09, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle10.setBackground(new java.awt.Color(0, 0, 0));
        circle10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle11.setBackground(new java.awt.Color(0, 0, 0));
        circle11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle12.setBackground(new java.awt.Color(0, 0, 0));
        circle12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle13.setBackground(new java.awt.Color(0, 0, 0));
        circle13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle14.setBackground(new java.awt.Color(0, 0, 0));
        circle14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle15.setBackground(new java.awt.Color(0, 0, 0));
        circle15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle16.setBackground(new java.awt.Color(0, 0, 0));
        circle16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle17.setBackground(new java.awt.Color(0, 0, 0));
        circle17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle18.setBackground(new java.awt.Color(0, 0, 0));
        circle18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle19.setBackground(new java.awt.Color(0, 0, 0));
        circle19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle20.setBackground(new java.awt.Color(0, 0, 0));
        circle20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle21.setBackground(new java.awt.Color(0, 0, 0));
        circle21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle22.setBackground(new java.awt.Color(0, 0, 0));
        circle22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle23.setBackground(new java.awt.Color(0, 0, 0));
        circle23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle24.setBackground(new java.awt.Color(0, 0, 0));
        circle24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle25.setBackground(new java.awt.Color(0, 0, 0));
        circle25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle26.setBackground(new java.awt.Color(0, 0, 0));
        circle26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle27.setBackground(new java.awt.Color(0, 0, 0));
        circle27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle28.setBackground(new java.awt.Color(0, 0, 0));
        circle28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle29.setBackground(new java.awt.Color(0, 0, 0));
        circle29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle30.setBackground(new java.awt.Color(0, 0, 0));
        circle30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle31.setBackground(new java.awt.Color(0, 0, 0));
        circle31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle32.setBackground(new java.awt.Color(0, 0, 0));
        circle32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle33.setBackground(new java.awt.Color(0, 0, 0));
        circle33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle34.setBackground(new java.awt.Color(0, 0, 0));
        circle34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle35.setBackground(new java.awt.Color(0, 0, 0));
        circle35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle36.setBackground(new java.awt.Color(0, 0, 0));
        circle36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle37.setBackground(new java.awt.Color(0, 0, 0));
        circle37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle38.setBackground(new java.awt.Color(0, 0, 0));
        circle38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle39.setBackground(new java.awt.Color(0, 0, 0));
        circle39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle40.setBackground(new java.awt.Color(0, 0, 0));
        circle40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle41.setBackground(new java.awt.Color(0, 0, 0));
        circle41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle42.setBackground(new java.awt.Color(0, 0, 0));
        circle42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle43.setBackground(new java.awt.Color(0, 0, 0));
        circle43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle44.setBackground(new java.awt.Color(0, 0, 0));
        circle44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle45.setBackground(new java.awt.Color(0, 0, 0));
        circle45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle46.setBackground(new java.awt.Color(0, 0, 0));
        circle46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle47.setBackground(new java.awt.Color(0, 0, 0));
        circle47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle48.setBackground(new java.awt.Color(0, 0, 0));
        circle48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle49.setBackground(new java.awt.Color(0, 0, 0));
        circle49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("©$Dollar Aksahy$");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 130, 20));

        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        num.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                numInputMethodTextChanged(evt);
            }
        });
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numKeyPressed(evt);
            }
        });
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 100, 30));

        buttonGroup1.add(amp);
        amp.setText("Amplitude");
        getContentPane().add(amp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));

        buttonGroup1.add(face);
        face.setText("Phase");
        getContentPane().add(face, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, -1, -1));

        buttonGroup1.add(lam);
        lam.setText("lamda");
        getContentPane().add(lam, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, -1, -1));

        buttonGroup1.add(omg);
        omg.setSelected(true);
        omg.setText("omega");
        getContentPane().add(omg, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        circle50.setBackground(new java.awt.Color(0, 0, 0));
        circle50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle51.setBackground(new java.awt.Color(0, 0, 0));
        circle51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle52.setBackground(new java.awt.Color(0, 0, 0));
        circle52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle53.setBackground(new java.awt.Color(0, 0, 0));
        circle53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle54.setBackground(new java.awt.Color(0, 0, 0));
        circle54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle55.setBackground(new java.awt.Color(0, 0, 0));
        circle55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle56.setBackground(new java.awt.Color(0, 0, 0));
        circle56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle57.setBackground(new java.awt.Color(0, 0, 0));
        circle57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle58.setBackground(new java.awt.Color(0, 0, 0));
        circle58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle59.setBackground(new java.awt.Color(0, 0, 0));
        circle59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle60.setBackground(new java.awt.Color(0, 0, 0));
        circle60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle61.setBackground(new java.awt.Color(0, 0, 0));
        circle61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle62.setBackground(new java.awt.Color(0, 0, 0));
        circle62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle63.setBackground(new java.awt.Color(0, 0, 0));
        circle63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle64.setBackground(new java.awt.Color(0, 0, 0));
        circle64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle65.setBackground(new java.awt.Color(0, 0, 0));
        circle65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle66.setBackground(new java.awt.Color(0, 0, 0));
        circle66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle67.setBackground(new java.awt.Color(0, 0, 0));
        circle67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle67, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle68.setBackground(new java.awt.Color(0, 0, 0));
        circle68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle68, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle69.setBackground(new java.awt.Color(0, 0, 0));
        circle69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle69, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle70.setBackground(new java.awt.Color(0, 0, 0));
        circle70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle71.setBackground(new java.awt.Color(0, 0, 0));
        circle71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle72.setBackground(new java.awt.Color(0, 0, 0));
        circle72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle73.setBackground(new java.awt.Color(0, 0, 0));
        circle73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle73, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle74.setBackground(new java.awt.Color(0, 0, 0));
        circle74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle75.setBackground(new java.awt.Color(0, 0, 0));
        circle75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle76.setBackground(new java.awt.Color(0, 0, 0));
        circle76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle76, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle77.setBackground(new java.awt.Color(0, 0, 0));
        circle77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle77, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle78.setBackground(new java.awt.Color(0, 0, 0));
        circle78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle79.setBackground(new java.awt.Color(0, 0, 0));
        circle79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle79, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle80.setBackground(new java.awt.Color(0, 0, 0));
        circle80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle80, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle81.setBackground(new java.awt.Color(0, 0, 0));
        circle81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle81, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle82.setBackground(new java.awt.Color(0, 0, 0));
        circle82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle82, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle83.setBackground(new java.awt.Color(0, 0, 0));
        circle83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle83, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle84.setBackground(new java.awt.Color(0, 0, 0));
        circle84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle84, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle85.setBackground(new java.awt.Color(0, 0, 0));
        circle85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle85, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle86.setBackground(new java.awt.Color(0, 0, 0));
        circle86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle86, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle87.setBackground(new java.awt.Color(0, 0, 0));
        circle87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle87, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle88.setBackground(new java.awt.Color(0, 0, 0));
        circle88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle88, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle89.setBackground(new java.awt.Color(0, 0, 0));
        circle89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle89, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle90.setBackground(new java.awt.Color(0, 0, 0));
        circle90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle90, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle91.setBackground(new java.awt.Color(0, 0, 0));
        circle91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle91, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle92.setBackground(new java.awt.Color(0, 0, 0));
        circle92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle92, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle93.setBackground(new java.awt.Color(0, 0, 0));
        circle93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle93, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle94.setBackground(new java.awt.Color(0, 0, 0));
        circle94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle94, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle95.setBackground(new java.awt.Color(0, 0, 0));
        circle95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle95, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle96.setBackground(new java.awt.Color(0, 0, 0));
        circle96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle96, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle97.setBackground(new java.awt.Color(0, 0, 0));
        circle97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle97, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle98.setBackground(new java.awt.Color(0, 0, 0));
        circle98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle98, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle99.setBackground(new java.awt.Color(0, 0, 0));
        circle99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle99, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        circle100.setBackground(new java.awt.Color(0, 0, 0));
        circle100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/electron.png"))); // NOI18N
        getContentPane().add(circle100, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x=100,y=200;
int A=30;
float t=0;
Timer timer;
float face_fact=(float) 3,lamda=(float)3,omega=(float) 1;

public void setPosition(Component c,int phi)
{
double pi = Math.PI;
y=(int)(A*Math.sin((omega*pi*t+phi*face_fact)));
c.setLocation((int)((x*t)-phi*lamda),y+200);
}

private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
timer.start();
}//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
timer.stop();
}//GEN-LAST:event_stopActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed

if(amp.isSelected()==true)
  A= (int) Float.parseFloat(num.getText());
else if(face.isSelected()==true)
  face_fact=Float.parseFloat(num.getText());
else if(lam.isSelected()==true)
  lamda=Float.parseFloat(num.getText());
else if(omg.isSelected()==true)
  omega=Float.parseFloat(num.getText());
timer.restart();
t=0;
        // TODO add your handling code here:
}//GEN-LAST:event_restartActionPerformed

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
restart.doClick();


    }//GEN-LAST:event_numActionPerformed

    private void numInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_numInputMethodTextChanged


    }//GEN-LAST:event_numInputMethodTextChanged

    private void numKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyPressed



    }//GEN-LAST:event_numKeyPressed


    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sinusoidal_wave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel circle01;
    private javax.swing.JLabel circle02;
    private javax.swing.JLabel circle03;
    private javax.swing.JLabel circle04;
    private javax.swing.JLabel circle05;
    private javax.swing.JLabel circle06;
    private javax.swing.JLabel circle07;
    private javax.swing.JLabel circle08;
    private javax.swing.JLabel circle09;
    private javax.swing.JLabel circle10;
    private javax.swing.JLabel circle100;
    private javax.swing.JLabel circle11;
    private javax.swing.JLabel circle12;
    private javax.swing.JLabel circle13;
    private javax.swing.JLabel circle14;
    private javax.swing.JLabel circle15;
    private javax.swing.JLabel circle16;
    private javax.swing.JLabel circle17;
    private javax.swing.JLabel circle18;
    private javax.swing.JLabel circle19;
    private javax.swing.JLabel circle20;
    private javax.swing.JLabel circle21;
    private javax.swing.JLabel circle22;
    private javax.swing.JLabel circle23;
    private javax.swing.JLabel circle24;
    private javax.swing.JLabel circle25;
    private javax.swing.JLabel circle26;
    private javax.swing.JLabel circle27;
    private javax.swing.JLabel circle28;
    private javax.swing.JLabel circle29;
    private javax.swing.JLabel circle30;
    private javax.swing.JLabel circle31;
    private javax.swing.JLabel circle32;
    private javax.swing.JLabel circle33;
    private javax.swing.JLabel circle34;
    private javax.swing.JLabel circle35;
    private javax.swing.JLabel circle36;
    private javax.swing.JLabel circle37;
    private javax.swing.JLabel circle38;
    private javax.swing.JLabel circle39;
    private javax.swing.JLabel circle40;
    private javax.swing.JLabel circle41;
    private javax.swing.JLabel circle42;
    private javax.swing.JLabel circle43;
    private javax.swing.JLabel circle44;
    private javax.swing.JLabel circle45;
    private javax.swing.JLabel circle46;
    private javax.swing.JLabel circle47;
    private javax.swing.JLabel circle48;
    private javax.swing.JLabel circle49;
    private javax.swing.JLabel circle50;
    private javax.swing.JLabel circle51;
    private javax.swing.JLabel circle52;
    private javax.swing.JLabel circle53;
    private javax.swing.JLabel circle54;
    private javax.swing.JLabel circle55;
    private javax.swing.JLabel circle56;
    private javax.swing.JLabel circle57;
    private javax.swing.JLabel circle58;
    private javax.swing.JLabel circle59;
    private javax.swing.JLabel circle60;
    private javax.swing.JLabel circle61;
    private javax.swing.JLabel circle62;
    private javax.swing.JLabel circle63;
    private javax.swing.JLabel circle64;
    private javax.swing.JLabel circle65;
    private javax.swing.JLabel circle66;
    private javax.swing.JLabel circle67;
    private javax.swing.JLabel circle68;
    private javax.swing.JLabel circle69;
    private javax.swing.JLabel circle70;
    private javax.swing.JLabel circle71;
    private javax.swing.JLabel circle72;
    private javax.swing.JLabel circle73;
    private javax.swing.JLabel circle74;
    private javax.swing.JLabel circle75;
    private javax.swing.JLabel circle76;
    private javax.swing.JLabel circle77;
    private javax.swing.JLabel circle78;
    private javax.swing.JLabel circle79;
    private javax.swing.JLabel circle80;
    private javax.swing.JLabel circle81;
    private javax.swing.JLabel circle82;
    private javax.swing.JLabel circle83;
    private javax.swing.JLabel circle84;
    private javax.swing.JLabel circle85;
    private javax.swing.JLabel circle86;
    private javax.swing.JLabel circle87;
    private javax.swing.JLabel circle88;
    private javax.swing.JLabel circle89;
    private javax.swing.JLabel circle90;
    private javax.swing.JLabel circle91;
    private javax.swing.JLabel circle92;
    private javax.swing.JLabel circle93;
    private javax.swing.JLabel circle94;
    private javax.swing.JLabel circle95;
    private javax.swing.JLabel circle96;
    private javax.swing.JLabel circle97;
    private javax.swing.JLabel circle98;
    private javax.swing.JLabel circle99;
    private javax.swing.JRadioButton face;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton lam;
    private javax.swing.JTextField num;
    private javax.swing.JRadioButton omg;
    private javax.swing.JButton restart;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables

}
