/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Simple_Programs;

/**
 *
 * @author $Akshay$
 */
public class Smiley_Mood_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Smiley_Mood_Calculator
     */
    public Smiley_Mood_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextArea_Scroll = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        con0 = new javax.swing.JSpinner();
        Smiley_1 = new javax.swing.JLabel();
        con1 = new javax.swing.JSpinner();
        Smiley_2 = new javax.swing.JLabel();
        con2 = new javax.swing.JSpinner();
        Smiley_3 = new javax.swing.JLabel();
        con3 = new javax.swing.JSpinner();
        Smiley_4 = new javax.swing.JLabel();
        con4 = new javax.swing.JSpinner();
        Smiley_5 = new javax.swing.JLabel();
        con5 = new javax.swing.JSpinner();
        Smiley_6 = new javax.swing.JLabel();
        con6 = new javax.swing.JSpinner();
        Smiley_7 = new javax.swing.JLabel();
        con7 = new javax.swing.JSpinner();
        Smiley_8 = new javax.swing.JLabel();
        con8 = new javax.swing.JSpinner();
        Smiley_9 = new javax.swing.JLabel();
        con9 = new javax.swing.JSpinner();
        Smiley_10 = new javax.swing.JLabel();
        con10 = new javax.swing.JSpinner();
        Smiley_11 = new javax.swing.JLabel();
        Smiley_12 = new javax.swing.JLabel();
        con11 = new javax.swing.JSpinner();
        Calculate = new javax.swing.JButton();
        mood_scroll = new javax.swing.JScrollPane();
        mood = new javax.swing.JTextArea();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chat.setBackground(new java.awt.Color(0, 0, 0));
        chat.setColumns(20);
        chat.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        chat.setForeground(new java.awt.Color(51, 204, 255));
        chat.setRows(5);
        TextArea_Scroll.setViewportView(chat);

        getContentPane().add(TextArea_Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 370, 155));

        con0.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con0, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 60, 30));

        Smiley_1.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_grin.png"))); // NOI18N
        Smiley_1.setOpaque(true);
        getContentPane().add(Smiley_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 30, 30));

        con1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 60, 30));

        Smiley_2.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_smile.png"))); // NOI18N
        Smiley_2.setOpaque(true);
        getContentPane().add(Smiley_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 30, 30));

        con2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 60, 30));

        Smiley_3.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_unsure.png"))); // NOI18N
        Smiley_3.setOpaque(true);
        getContentPane().add(Smiley_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 30, 30));

        con3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 60, 30));

        Smiley_4.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_frown.png"))); // NOI18N
        Smiley_4.setOpaque(true);
        getContentPane().add(Smiley_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 30, 30));

        con4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 60, 30));

        Smiley_5.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_cry.png"))); // NOI18N
        Smiley_5.setOpaque(true);
        getContentPane().add(Smiley_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 30, 30));

        con5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 60, 30));

        Smiley_6.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_wink.png"))); // NOI18N
        Smiley_6.setOpaque(true);
        getContentPane().add(Smiley_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 30, 30));

        con6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 60, 30));

        Smiley_7.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_heart.png"))); // NOI18N
        Smiley_7.setOpaque(true);
        getContentPane().add(Smiley_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 30, 30));

        con7.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 60, 30));

        Smiley_8.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_kiss.png"))); // NOI18N
        Smiley_8.setOpaque(true);
        getContentPane().add(Smiley_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 30, 30));

        con8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 60, 30));

        Smiley_9.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_confused.png"))); // NOI18N
        Smiley_9.setOpaque(true);
        getContentPane().add(Smiley_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 30, 30));

        con9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 60, 30));

        Smiley_10.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_gasp.png"))); // NOI18N
        Smiley_10.setOpaque(true);
        getContentPane().add(Smiley_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 30, 30));

        con10.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 60, 30));

        Smiley_11.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/Smiley_tongue.png"))); // NOI18N
        Smiley_11.setOpaque(true);
        getContentPane().add(Smiley_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 30, 30));

        Smiley_12.setBackground(new java.awt.Color(255, 255, 255));
        Smiley_12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Smiley_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smiley_12.setText(":')");
        Smiley_12.setOpaque(true);
        getContentPane().add(Smiley_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 30, 30));

        con11.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(con11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 60, 30));

        Calculate.setBackground(new java.awt.Color(0, 0, 0));
        Calculate.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        Calculate.setForeground(new java.awt.Color(0, 153, 255));
        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });
        getContentPane().add(Calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 240, 50));

        mood_scroll.setBorder(null);

        mood.setColumns(20);
        mood.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        mood.setRows(5);
        mood.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mood Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        mood_scroll.setViewportView(mood);

        getContentPane().add(mood_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 290, 330));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 153, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Smiley Clalculator");
        Title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Title.setOpaque(true);
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int searchString(String main,String sub)
{
int times=0;
int ml = main.length();
int sl = sub.length();
for(int i=0;i<=ml-sl;i++)
{
if(main.substring(i,i+sl).equals(sub))
times++;
}
return times;
}  
    
    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
String text = chat.getText();
con0.setValue(searchString(text,":D"));
con1.setValue(searchString(text,":)"));
con2.setValue(searchString(text,":/")+searchString(text,":\\"));
con3.setValue(searchString(text,":("));
con4.setValue(searchString(text,":'("));
con5.setValue(searchString(text,";)"));
con6.setValue(searchString(text,"<3")+searchString(text,"♥"));
con7.setValue(searchString(text,":*"));
con8.setValue(searchString(text,"o.O")+searchString(text,"O.o"));
con9.setValue(searchString(text,":O")+searchString(text,":o"));
con10.setValue(searchString(text,":P")+searchString(text,":p"));
con11.setValue(searchString(text,":')"));

int m0 =(int)con0.getValue(); 
int m1 =(int)con1.getValue(); 
int m2 =(int)con2.getValue(); 
int m3 =(int)con3.getValue(); 
int m4 =(int)con4.getValue(); 
int m5 =(int)con5.getValue(); 
int m6 =(int)con6.getValue(); 
int m7 =(int)con7.getValue(); 
int m8 =(int)con8.getValue(); 
int m9 =(int)con9.getValue(); 
int m10 =(int)con10.getValue(); 
int m11 =(int)con11.getValue();
int smileys = m0+m1+m2+m3+m4+m5+m6+m7+m8+m9+m10+m11;
int total = (m0*2)+m1+m2+m3+(m4*2)+m5+(m6*2)+m7+m8+m9+m10+(m11*2);
float happy = (m0*2)+m1+m5+(m11*2);
happy=happy*100;
happy=happy/total;
float sad = m2+m3+(m4*2);
sad=sad*100;
sad=sad/total;
float love = (m6*2)+m7;
love=love*100;
love=love/total;
float conf = m8*100;
conf=conf/total;
float shock = m9*100;
shock=shock/total;
float bored = m10*100;
bored=bored/total;
float perc = happy+sad+love+conf+shock+bored;
mood.setText(""
+" Here is your Mood Results :- \n" 
+" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ " 
+"\n Happy           : "+happy+"%"
+"\n Sad/Depressed   : "+sad+"%"
+"\n Love            : "+love+"%"
+"\n Confused        : "+conf+"%"
+"\n Shock/Surprised : "+shock+"%"
+"\n Bored           : "+bored+"%"
+"\n Total Smileys   : "+smileys+""
+"\n Total Smiley Pts: "+total+" pts."
+"\n Total Mood perc : "+perc+"%"
        
);            
    }//GEN-LAST:event_CalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Smiley_Mood_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Smiley_Mood_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Smiley_Mood_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Smiley_Mood_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Smiley_Mood_Calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculate;
    private javax.swing.JLabel Smiley_1;
    private javax.swing.JLabel Smiley_10;
    private javax.swing.JLabel Smiley_11;
    private javax.swing.JLabel Smiley_12;
    private javax.swing.JLabel Smiley_2;
    private javax.swing.JLabel Smiley_3;
    private javax.swing.JLabel Smiley_4;
    private javax.swing.JLabel Smiley_5;
    private javax.swing.JLabel Smiley_6;
    private javax.swing.JLabel Smiley_7;
    private javax.swing.JLabel Smiley_8;
    private javax.swing.JLabel Smiley_9;
    private javax.swing.JScrollPane TextArea_Scroll;
    private javax.swing.JLabel Title;
    private javax.swing.JTextArea chat;
    private javax.swing.JSpinner con0;
    private javax.swing.JSpinner con1;
    private javax.swing.JSpinner con10;
    private javax.swing.JSpinner con11;
    private javax.swing.JSpinner con2;
    private javax.swing.JSpinner con3;
    private javax.swing.JSpinner con4;
    private javax.swing.JSpinner con5;
    private javax.swing.JSpinner con6;
    private javax.swing.JSpinner con7;
    private javax.swing.JSpinner con8;
    private javax.swing.JSpinner con9;
    private javax.swing.JTextArea mood;
    private javax.swing.JScrollPane mood_scroll;
    // End of variables declaration//GEN-END:variables
}
