/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * The_Physical_World.java
 *
 * Created on Jan 9, 2012, 11:16:17 AM
 */

package Simple_Programs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author student
 */
public class The_Physical_World extends javax.swing.JFrame {

    /** Creates new form The_Physical_World */
    public The_Physical_World() {
        initComponents();
           tmr1 = new Timer(10,
           new ActionListener(){
           public void actionPerformed(ActionEvent e){
            if(y>400)
            {
             vy=-vy*8/10;
            }

            if(grip==false){
            if(y<=400)
            vy+=g;
            y+=vy;

            basketball.setLocation((int)(x+vx),(int)y);

           }

           

           }});
        tmr1.start();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basketball = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basketball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/other_Program_Images/basketball.png"))); // NOI18N
        basketball.setToolTipText("");
        basketball.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        basketball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                basketballMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                basketballMouseReleased(evt);
            }
        });
        basketball.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                basketballMouseDragged(evt);
            }
        });
        getContentPane().add(basketball, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 100));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 20, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Timer tmr1,tmr2;//Timer

final float g=(float) 0.1;//Gravity
float vx=0,vy=0;//Final Speeds
int ux,uy;//Initial Speeds

int i=0;
float y=10,x=200;
int dx,dy;
boolean grip=false;



private void basketballMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basketballMouseDragged
grip=true;
if((basketball.getY()!=500)||(basketball.getY()!=500)){

if(i==0){
x=basketball.getX();
y=basketball.getY();
dx =            (int) (getMousePosition().x - x);
dy =            (int) (getMousePosition().y - y);
}
x=getMousePosition().x-dx;
y=getMousePosition().y-dy;
basketball.setLocation((int)x,(int)y);
i++;


}
}//GEN-LAST:event_basketballMouseDragged

private void basketballMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basketballMouseReleased
i=0;
grip=false;
vy=0;
}//GEN-LAST:event_basketballMouseReleased

private void basketballMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_basketballMouseClicked
grip=false;
}//GEN-LAST:event_basketballMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new The_Physical_World().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basketball;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
