/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Wave_Motion.java
 *
 * Created on Dec 8, 2011, 5:16:12 PM
 */
package Simple_Programs;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/**
 *
 * @author $Akshay$
 */
public class Wave_Motion extends javax.swing.JFrame {

    /** Creates new form Wave_Motion */
    public Wave_Motion() {
        initComponents();
        motion = new Timer(25,new ActionListener(){
        public void actionPerformed(ActionEvent e){

wave(circle1,1);wave(circle2,2);wave(circle3,3);wave(circle4,4);wave(circle5,5);wave(circle6,6);wave(circle7,7);wave(circle8,8);wave(circle9,9);wave(circle10,10);
wave(circle11,11);wave(circle12,12);wave(circle13,13);wave(circle14,14);wave(circle15,15);wave(circle16,16);wave(circle17,17);wave(circle18,18);wave(circle19,19);wave(circle20,20);
wave(circle21,21);wave(circle22,22);wave(circle23,23);wave(circle24,24);wave(circle25,25);wave(circle26,26);wave(circle27,27);wave(circle28,28);wave(circle29,29);wave(circle30,30);
wave(circle31,31);wave(circle32,32);wave(circle33,33);wave(circle34,34);wave(circle35,35);wave(circle36,36);wave(circle37,37);wave(circle38,38);wave(circle39,39);wave(circle40,40);
wave(circle41,41);wave(circle42,42);wave(circle43,43);wave(circle44,44);wave(circle45,45);wave(circle46,46);wave(circle47,47);wave(circle48,48);wave(circle49,49);wave(circle50,50);
wave(circle51,51);wave(circle52,52);wave(circle53,53);wave(circle54,54);wave(circle55,55);wave(circle56,56);wave(circle57,57);wave(circle58,58);wave(circle59,59);wave(circle60,60);
wave(circle61,61);wave(circle62,62);wave(circle63,63);wave(circle64,64);wave(circle65,65);wave(circle66,66);wave(circle67,67);wave(circle68,68);wave(circle69,69);wave(circle70,70);
wave(circle71,71);wave(circle72,72);wave(circle73,73);wave(circle74,74);wave(circle75,75);wave(circle76,76);wave(circle77,77);wave(circle78,78);wave(circle79,79);wave(circle80,80);
wave(circle81,81);wave(circle82,82);wave(circle83,83);wave(circle84,84);wave(circle85,85);wave(circle86,86);wave(circle87,87);wave(circle88,88);wave(circle89,89);wave(circle90,90);
wave(circle91,91);wave(circle92,92);wave(circle93,93);wave(circle94,94);wave(circle95,95);wave(circle96,96);wave(circle97,97);wave(circle98,98);wave(circle99,99);wave(circle100,100);

t= (float)(t+0.05);
        }
    });
    motion.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circle1 = new javax.swing.JLabel();
        circle2 = new javax.swing.JLabel();
        circle3 = new javax.swing.JLabel();
        circle4 = new javax.swing.JLabel();
        circle5 = new javax.swing.JLabel();
        circle6 = new javax.swing.JLabel();
        circle7 = new javax.swing.JLabel();
        circle8 = new javax.swing.JLabel();
        circle9 = new javax.swing.JLabel();
        circle10 = new javax.swing.JLabel();
        circle11 = new javax.swing.JLabel();
        circle12 = new javax.swing.JLabel();
        circle13 = new javax.swing.JLabel();
        circle14 = new javax.swing.JLabel();
        circle15 = new javax.swing.JLabel();
        circle16 = new javax.swing.JLabel();
        circle17 = new javax.swing.JLabel();
        circle18 = new javax.swing.JLabel();
        circle19 = new javax.swing.JLabel();
        circle20 = new javax.swing.JLabel();
        circle21 = new javax.swing.JLabel();
        circle22 = new javax.swing.JLabel();
        circle23 = new javax.swing.JLabel();
        circle24 = new javax.swing.JLabel();
        circle25 = new javax.swing.JLabel();
        circle26 = new javax.swing.JLabel();
        circle27 = new javax.swing.JLabel();
        circle28 = new javax.swing.JLabel();
        circle29 = new javax.swing.JLabel();
        circle30 = new javax.swing.JLabel();
        circle31 = new javax.swing.JLabel();
        circle32 = new javax.swing.JLabel();
        circle33 = new javax.swing.JLabel();
        circle34 = new javax.swing.JLabel();
        circle35 = new javax.swing.JLabel();
        circle36 = new javax.swing.JLabel();
        circle37 = new javax.swing.JLabel();
        circle38 = new javax.swing.JLabel();
        circle39 = new javax.swing.JLabel();
        circle40 = new javax.swing.JLabel();
        circle41 = new javax.swing.JLabel();
        circle42 = new javax.swing.JLabel();
        circle43 = new javax.swing.JLabel();
        circle44 = new javax.swing.JLabel();
        circle45 = new javax.swing.JLabel();
        circle46 = new javax.swing.JLabel();
        circle47 = new javax.swing.JLabel();
        circle48 = new javax.swing.JLabel();
        circle49 = new javax.swing.JLabel();
        circle50 = new javax.swing.JLabel();
        circle51 = new javax.swing.JLabel();
        circle52 = new javax.swing.JLabel();
        circle53 = new javax.swing.JLabel();
        circle54 = new javax.swing.JLabel();
        circle55 = new javax.swing.JLabel();
        circle56 = new javax.swing.JLabel();
        circle57 = new javax.swing.JLabel();
        circle58 = new javax.swing.JLabel();
        circle59 = new javax.swing.JLabel();
        circle60 = new javax.swing.JLabel();
        circle61 = new javax.swing.JLabel();
        circle62 = new javax.swing.JLabel();
        circle63 = new javax.swing.JLabel();
        circle64 = new javax.swing.JLabel();
        circle65 = new javax.swing.JLabel();
        circle66 = new javax.swing.JLabel();
        circle67 = new javax.swing.JLabel();
        circle68 = new javax.swing.JLabel();
        circle69 = new javax.swing.JLabel();
        circle70 = new javax.swing.JLabel();
        circle71 = new javax.swing.JLabel();
        circle72 = new javax.swing.JLabel();
        circle73 = new javax.swing.JLabel();
        circle74 = new javax.swing.JLabel();
        circle75 = new javax.swing.JLabel();
        circle76 = new javax.swing.JLabel();
        circle77 = new javax.swing.JLabel();
        circle78 = new javax.swing.JLabel();
        circle79 = new javax.swing.JLabel();
        circle80 = new javax.swing.JLabel();
        circle81 = new javax.swing.JLabel();
        circle82 = new javax.swing.JLabel();
        circle83 = new javax.swing.JLabel();
        circle84 = new javax.swing.JLabel();
        circle85 = new javax.swing.JLabel();
        circle86 = new javax.swing.JLabel();
        circle87 = new javax.swing.JLabel();
        circle88 = new javax.swing.JLabel();
        circle89 = new javax.swing.JLabel();
        circle90 = new javax.swing.JLabel();
        circle91 = new javax.swing.JLabel();
        circle92 = new javax.swing.JLabel();
        circle93 = new javax.swing.JLabel();
        circle94 = new javax.swing.JLabel();
        circle95 = new javax.swing.JLabel();
        circle96 = new javax.swing.JLabel();
        circle97 = new javax.swing.JLabel();
        circle98 = new javax.swing.JLabel();
        circle99 = new javax.swing.JLabel();
        circle100 = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        stop = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        restart1 = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circle1.setBackground(new java.awt.Color(255, 0, 0));
        circle1.setOpaque(true);
        getContentPane().add(circle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 2, 2));

        circle2.setBackground(new java.awt.Color(255, 0, 0));
        circle2.setOpaque(true);
        getContentPane().add(circle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 2, 2));

        circle3.setBackground(new java.awt.Color(255, 0, 0));
        circle3.setOpaque(true);
        getContentPane().add(circle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 2, 2));

        circle4.setBackground(new java.awt.Color(255, 0, 0));
        circle4.setOpaque(true);
        getContentPane().add(circle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 2, 2));

        circle5.setBackground(new java.awt.Color(255, 0, 0));
        circle5.setOpaque(true);
        getContentPane().add(circle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 2, 2));

        circle6.setBackground(new java.awt.Color(255, 0, 0));
        circle6.setOpaque(true);
        getContentPane().add(circle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 2, 2));

        circle7.setBackground(new java.awt.Color(255, 0, 0));
        circle7.setOpaque(true);
        getContentPane().add(circle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 2, 2));

        circle8.setBackground(new java.awt.Color(255, 0, 0));
        circle8.setOpaque(true);
        getContentPane().add(circle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 2, 2));

        circle9.setBackground(new java.awt.Color(255, 0, 0));
        circle9.setOpaque(true);
        getContentPane().add(circle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 2, 2));

        circle10.setBackground(new java.awt.Color(255, 0, 0));
        circle10.setOpaque(true);
        getContentPane().add(circle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 2, 2));

        circle11.setBackground(new java.awt.Color(255, 0, 0));
        circle11.setOpaque(true);
        getContentPane().add(circle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 2, 2));

        circle12.setBackground(new java.awt.Color(255, 0, 0));
        circle12.setOpaque(true);
        getContentPane().add(circle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 2, 2));

        circle13.setBackground(new java.awt.Color(255, 0, 0));
        circle13.setOpaque(true);
        getContentPane().add(circle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 2, 2));

        circle14.setBackground(new java.awt.Color(255, 0, 0));
        circle14.setOpaque(true);
        getContentPane().add(circle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 2, 2));

        circle15.setBackground(new java.awt.Color(255, 0, 0));
        circle15.setOpaque(true);
        getContentPane().add(circle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 2, 2));

        circle16.setBackground(new java.awt.Color(255, 0, 0));
        circle16.setOpaque(true);
        getContentPane().add(circle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 2, 2));

        circle17.setBackground(new java.awt.Color(255, 0, 0));
        circle17.setOpaque(true);
        getContentPane().add(circle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 2, 2));

        circle18.setBackground(new java.awt.Color(255, 0, 0));
        circle18.setOpaque(true);
        getContentPane().add(circle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 2, 2));

        circle19.setBackground(new java.awt.Color(255, 0, 0));
        circle19.setOpaque(true);
        getContentPane().add(circle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 2, 2));

        circle20.setBackground(new java.awt.Color(255, 0, 0));
        circle20.setOpaque(true);
        getContentPane().add(circle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 2, 2));

        circle21.setBackground(new java.awt.Color(255, 0, 0));
        circle21.setOpaque(true);
        getContentPane().add(circle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle22.setBackground(new java.awt.Color(255, 0, 0));
        circle22.setOpaque(true);
        getContentPane().add(circle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 2, 2));

        circle23.setBackground(new java.awt.Color(255, 0, 0));
        circle23.setOpaque(true);
        getContentPane().add(circle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 2, 2));

        circle24.setBackground(new java.awt.Color(255, 0, 0));
        circle24.setOpaque(true);
        getContentPane().add(circle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 2, 2));

        circle25.setBackground(new java.awt.Color(255, 0, 0));
        circle25.setOpaque(true);
        getContentPane().add(circle25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 2, 2));

        circle26.setBackground(new java.awt.Color(255, 0, 0));
        circle26.setOpaque(true);
        getContentPane().add(circle26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 2, 2));

        circle27.setBackground(new java.awt.Color(255, 0, 0));
        circle27.setOpaque(true);
        getContentPane().add(circle27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 2, 2));

        circle28.setBackground(new java.awt.Color(255, 0, 0));
        circle28.setOpaque(true);
        getContentPane().add(circle28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 2, 2));

        circle29.setBackground(new java.awt.Color(255, 0, 0));
        circle29.setOpaque(true);
        getContentPane().add(circle29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 2, 2));

        circle30.setBackground(new java.awt.Color(255, 0, 0));
        circle30.setOpaque(true);
        getContentPane().add(circle30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 2, 2));

        circle31.setBackground(new java.awt.Color(255, 0, 0));
        circle31.setOpaque(true);
        getContentPane().add(circle31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 2, 2));

        circle32.setBackground(new java.awt.Color(255, 0, 0));
        circle32.setOpaque(true);
        getContentPane().add(circle32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 2, 2));

        circle33.setBackground(new java.awt.Color(255, 0, 0));
        circle33.setOpaque(true);
        getContentPane().add(circle33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 2, 2));

        circle34.setBackground(new java.awt.Color(255, 0, 0));
        circle34.setOpaque(true);
        getContentPane().add(circle34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 2, 2));

        circle35.setBackground(new java.awt.Color(255, 0, 0));
        circle35.setOpaque(true);
        getContentPane().add(circle35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 2, 2));

        circle36.setBackground(new java.awt.Color(255, 0, 0));
        circle36.setOpaque(true);
        getContentPane().add(circle36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 2, 2));

        circle37.setBackground(new java.awt.Color(255, 0, 0));
        circle37.setOpaque(true);
        getContentPane().add(circle37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 2, 2));

        circle38.setBackground(new java.awt.Color(255, 0, 0));
        circle38.setOpaque(true);
        getContentPane().add(circle38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 2, 2));

        circle39.setBackground(new java.awt.Color(255, 0, 0));
        circle39.setOpaque(true);
        getContentPane().add(circle39, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 2, 2));

        circle40.setBackground(new java.awt.Color(255, 0, 0));
        circle40.setOpaque(true);
        getContentPane().add(circle40, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 2, 2));

        circle41.setBackground(new java.awt.Color(255, 0, 0));
        circle41.setOpaque(true);
        getContentPane().add(circle41, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 2, 2));

        circle42.setBackground(new java.awt.Color(255, 0, 0));
        circle42.setOpaque(true);
        getContentPane().add(circle42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 2, 2));

        circle43.setBackground(new java.awt.Color(255, 0, 0));
        circle43.setOpaque(true);
        getContentPane().add(circle43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 2, 2));

        circle44.setBackground(new java.awt.Color(255, 0, 0));
        circle44.setOpaque(true);
        getContentPane().add(circle44, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 2, 2));

        circle45.setBackground(new java.awt.Color(255, 0, 0));
        circle45.setOpaque(true);
        getContentPane().add(circle45, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 2, 2));

        circle46.setBackground(new java.awt.Color(255, 0, 0));
        circle46.setOpaque(true);
        getContentPane().add(circle46, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 104, 2, 2));

        circle47.setBackground(new java.awt.Color(255, 0, 0));
        circle47.setOpaque(true);
        getContentPane().add(circle47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 2, 2));

        circle48.setBackground(new java.awt.Color(255, 0, 0));
        circle48.setOpaque(true);
        getContentPane().add(circle48, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 2, 2));

        circle49.setBackground(new java.awt.Color(255, 0, 0));
        circle49.setOpaque(true);
        getContentPane().add(circle49, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 2, 2));

        circle50.setBackground(new java.awt.Color(255, 0, 0));
        circle50.setOpaque(true);
        getContentPane().add(circle50, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 2, 2));

        circle51.setBackground(new java.awt.Color(255, 0, 0));
        circle51.setOpaque(true);
        getContentPane().add(circle51, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 2, 2));

        circle52.setBackground(new java.awt.Color(255, 0, 0));
        circle52.setOpaque(true);
        getContentPane().add(circle52, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 2, 2));

        circle53.setBackground(new java.awt.Color(255, 0, 0));
        circle53.setOpaque(true);
        getContentPane().add(circle53, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle54.setBackground(new java.awt.Color(255, 0, 0));
        circle54.setOpaque(true);
        getContentPane().add(circle54, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle55.setBackground(new java.awt.Color(255, 0, 0));
        circle55.setOpaque(true);
        getContentPane().add(circle55, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle56.setBackground(new java.awt.Color(255, 0, 0));
        circle56.setOpaque(true);
        getContentPane().add(circle56, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle57.setBackground(new java.awt.Color(255, 0, 0));
        circle57.setOpaque(true);
        getContentPane().add(circle57, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle58.setBackground(new java.awt.Color(255, 0, 0));
        circle58.setOpaque(true);
        getContentPane().add(circle58, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle59.setBackground(new java.awt.Color(255, 0, 0));
        circle59.setOpaque(true);
        getContentPane().add(circle59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle60.setBackground(new java.awt.Color(255, 0, 0));
        circle60.setOpaque(true);
        getContentPane().add(circle60, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle61.setBackground(new java.awt.Color(255, 0, 0));
        circle61.setOpaque(true);
        getContentPane().add(circle61, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle62.setBackground(new java.awt.Color(255, 0, 0));
        circle62.setOpaque(true);
        getContentPane().add(circle62, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle63.setBackground(new java.awt.Color(255, 0, 0));
        circle63.setOpaque(true);
        getContentPane().add(circle63, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle64.setBackground(new java.awt.Color(255, 0, 0));
        circle64.setOpaque(true);
        getContentPane().add(circle64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle65.setBackground(new java.awt.Color(255, 0, 0));
        circle65.setOpaque(true);
        getContentPane().add(circle65, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle66.setBackground(new java.awt.Color(255, 0, 0));
        circle66.setOpaque(true);
        getContentPane().add(circle66, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle67.setBackground(new java.awt.Color(255, 0, 0));
        circle67.setOpaque(true);
        getContentPane().add(circle67, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle68.setBackground(new java.awt.Color(255, 0, 0));
        circle68.setOpaque(true);
        getContentPane().add(circle68, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle69.setBackground(new java.awt.Color(255, 0, 0));
        circle69.setOpaque(true);
        getContentPane().add(circle69, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle70.setBackground(new java.awt.Color(255, 0, 0));
        circle70.setOpaque(true);
        getContentPane().add(circle70, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle71.setBackground(new java.awt.Color(255, 0, 0));
        circle71.setOpaque(true);
        getContentPane().add(circle71, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle72.setBackground(new java.awt.Color(255, 0, 0));
        circle72.setOpaque(true);
        getContentPane().add(circle72, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle73.setBackground(new java.awt.Color(255, 0, 0));
        circle73.setOpaque(true);
        getContentPane().add(circle73, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle74.setBackground(new java.awt.Color(255, 0, 0));
        circle74.setOpaque(true);
        getContentPane().add(circle74, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle75.setBackground(new java.awt.Color(255, 0, 0));
        circle75.setOpaque(true);
        getContentPane().add(circle75, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle76.setBackground(new java.awt.Color(255, 0, 0));
        circle76.setOpaque(true);
        getContentPane().add(circle76, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle77.setBackground(new java.awt.Color(255, 0, 0));
        circle77.setOpaque(true);
        getContentPane().add(circle77, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle78.setBackground(new java.awt.Color(255, 0, 0));
        circle78.setOpaque(true);
        getContentPane().add(circle78, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle79.setBackground(new java.awt.Color(255, 0, 0));
        circle79.setOpaque(true);
        getContentPane().add(circle79, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle80.setBackground(new java.awt.Color(255, 0, 0));
        circle80.setOpaque(true);
        getContentPane().add(circle80, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle81.setBackground(new java.awt.Color(255, 0, 0));
        circle81.setOpaque(true);
        getContentPane().add(circle81, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle82.setBackground(new java.awt.Color(255, 0, 0));
        circle82.setOpaque(true);
        getContentPane().add(circle82, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle83.setBackground(new java.awt.Color(255, 0, 0));
        circle83.setOpaque(true);
        getContentPane().add(circle83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle84.setBackground(new java.awt.Color(255, 0, 0));
        circle84.setOpaque(true);
        getContentPane().add(circle84, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle85.setBackground(new java.awt.Color(255, 0, 0));
        circle85.setOpaque(true);
        getContentPane().add(circle85, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle86.setBackground(new java.awt.Color(255, 0, 0));
        circle86.setOpaque(true);
        getContentPane().add(circle86, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle87.setBackground(new java.awt.Color(255, 0, 0));
        circle87.setOpaque(true);
        getContentPane().add(circle87, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle88.setBackground(new java.awt.Color(255, 0, 0));
        circle88.setOpaque(true);
        getContentPane().add(circle88, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle89.setBackground(new java.awt.Color(255, 0, 0));
        circle89.setOpaque(true);
        getContentPane().add(circle89, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle90.setBackground(new java.awt.Color(255, 0, 0));
        circle90.setOpaque(true);
        getContentPane().add(circle90, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle91.setBackground(new java.awt.Color(255, 0, 0));
        circle91.setOpaque(true);
        getContentPane().add(circle91, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle92.setBackground(new java.awt.Color(255, 0, 0));
        circle92.setOpaque(true);
        getContentPane().add(circle92, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle93.setBackground(new java.awt.Color(255, 0, 0));
        circle93.setOpaque(true);
        getContentPane().add(circle93, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle94.setBackground(new java.awt.Color(255, 0, 0));
        circle94.setOpaque(true);
        getContentPane().add(circle94, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle95.setBackground(new java.awt.Color(255, 0, 0));
        circle95.setOpaque(true);
        getContentPane().add(circle95, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle96.setBackground(new java.awt.Color(255, 0, 0));
        circle96.setOpaque(true);
        getContentPane().add(circle96, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle97.setBackground(new java.awt.Color(255, 0, 0));
        circle97.setOpaque(true);
        getContentPane().add(circle97, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle98.setBackground(new java.awt.Color(255, 0, 0));
        circle98.setOpaque(true);
        getContentPane().add(circle98, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle99.setBackground(new java.awt.Color(255, 0, 0));
        circle99.setOpaque(true);
        getContentPane().add(circle99, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        circle100.setBackground(new java.awt.Color(255, 0, 0));
        circle100.setOpaque(true);
        getContentPane().add(circle100, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 2, 2));

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 1, true), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0))));
        user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stop.setBackground(new java.awt.Color(0, 0, 0));
        stop.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 0, 0));
        stop.setText("Start");
        stop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        stop.setFocusable(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        user.add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 110, 40));

        pause.setBackground(new java.awt.Color(0, 0, 0));
        pause.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        pause.setForeground(new java.awt.Color(255, 255, 0));
        pause.setText("Pause");
        pause.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pause.setFocusable(false);
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        user.add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 110, 40));

        restart1.setBackground(new java.awt.Color(0, 0, 0));
        restart1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        restart1.setForeground(new java.awt.Color(0, 102, 255));
        restart1.setText("Amplitude");
        restart1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        restart1.setFocusable(false);
        restart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restart1ActionPerformed(evt);
            }
        });
        user.add(restart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, 40));

        restart.setBackground(new java.awt.Color(0, 0, 0));
        restart.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        restart.setForeground(new java.awt.Color(0, 204, 0));
        restart.setText("Restart");
        restart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        restart.setFocusable(false);
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        user.add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 5, 110, 40));

        jTextField1.setText("5");
        user.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 110, 40));

        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 540, 100));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int A=10;//Amplitude
float t=0;//Time
int lamda=3;//Lamda :P
float phase=(float)0.1;//Phase
float omega=0.5f;//Omega
int x=20,y=0;//Fundamental X and Y Co-ordinates of the Labels :)

void wave(Component c,int p)
{
y =(int)(A*Math.sin(3.1416*omega*t + p*phase));
c.setLocation((int)(x*t-p*lamda),(int)(y+200));
    
}

    
    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
motion.restart();  
t=0;
    }//GEN-LAST:event_restartActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
motion.start();
    }//GEN-LAST:event_stopActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
motion.stop();     
    }//GEN-LAST:event_pauseActionPerformed

    private void restart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restart1ActionPerformed
Timer motion;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wave_Motion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wave_Motion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wave_Motion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wave_Motion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Wave_Motion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circle1;
    private javax.swing.JLabel circle10;
    private javax.swing.JLabel circle100;
    private javax.swing.JLabel circle11;
    private javax.swing.JLabel circle12;
    private javax.swing.JLabel circle13;
    private javax.swing.JLabel circle14;
    private javax.swing.JLabel circle15;
    private javax.swing.JLabel circle16;
    private javax.swing.JLabel circle17;
    private javax.swing.JLabel circle18;
    private javax.swing.JLabel circle19;
    private javax.swing.JLabel circle2;
    private javax.swing.JLabel circle20;
    private javax.swing.JLabel circle21;
    private javax.swing.JLabel circle22;
    private javax.swing.JLabel circle23;
    private javax.swing.JLabel circle24;
    private javax.swing.JLabel circle25;
    private javax.swing.JLabel circle26;
    private javax.swing.JLabel circle27;
    private javax.swing.JLabel circle28;
    private javax.swing.JLabel circle29;
    private javax.swing.JLabel circle3;
    private javax.swing.JLabel circle30;
    private javax.swing.JLabel circle31;
    private javax.swing.JLabel circle32;
    private javax.swing.JLabel circle33;
    private javax.swing.JLabel circle34;
    private javax.swing.JLabel circle35;
    private javax.swing.JLabel circle36;
    private javax.swing.JLabel circle37;
    private javax.swing.JLabel circle38;
    private javax.swing.JLabel circle39;
    private javax.swing.JLabel circle4;
    private javax.swing.JLabel circle40;
    private javax.swing.JLabel circle41;
    private javax.swing.JLabel circle42;
    private javax.swing.JLabel circle43;
    private javax.swing.JLabel circle44;
    private javax.swing.JLabel circle45;
    private javax.swing.JLabel circle46;
    private javax.swing.JLabel circle47;
    private javax.swing.JLabel circle48;
    private javax.swing.JLabel circle49;
    private javax.swing.JLabel circle5;
    private javax.swing.JLabel circle50;
    private javax.swing.JLabel circle51;
    private javax.swing.JLabel circle52;
    private javax.swing.JLabel circle53;
    private javax.swing.JLabel circle54;
    private javax.swing.JLabel circle55;
    private javax.swing.JLabel circle56;
    private javax.swing.JLabel circle57;
    private javax.swing.JLabel circle58;
    private javax.swing.JLabel circle59;
    private javax.swing.JLabel circle6;
    private javax.swing.JLabel circle60;
    private javax.swing.JLabel circle61;
    private javax.swing.JLabel circle62;
    private javax.swing.JLabel circle63;
    private javax.swing.JLabel circle64;
    private javax.swing.JLabel circle65;
    private javax.swing.JLabel circle66;
    private javax.swing.JLabel circle67;
    private javax.swing.JLabel circle68;
    private javax.swing.JLabel circle69;
    private javax.swing.JLabel circle7;
    private javax.swing.JLabel circle70;
    private javax.swing.JLabel circle71;
    private javax.swing.JLabel circle72;
    private javax.swing.JLabel circle73;
    private javax.swing.JLabel circle74;
    private javax.swing.JLabel circle75;
    private javax.swing.JLabel circle76;
    private javax.swing.JLabel circle77;
    private javax.swing.JLabel circle78;
    private javax.swing.JLabel circle79;
    private javax.swing.JLabel circle8;
    private javax.swing.JLabel circle80;
    private javax.swing.JLabel circle81;
    private javax.swing.JLabel circle82;
    private javax.swing.JLabel circle83;
    private javax.swing.JLabel circle84;
    private javax.swing.JLabel circle85;
    private javax.swing.JLabel circle86;
    private javax.swing.JLabel circle87;
    private javax.swing.JLabel circle88;
    private javax.swing.JLabel circle89;
    private javax.swing.JLabel circle9;
    private javax.swing.JLabel circle90;
    private javax.swing.JLabel circle91;
    private javax.swing.JLabel circle92;
    private javax.swing.JLabel circle93;
    private javax.swing.JLabel circle94;
    private javax.swing.JLabel circle95;
    private javax.swing.JLabel circle96;
    private javax.swing.JLabel circle97;
    private javax.swing.JLabel circle98;
    private javax.swing.JLabel circle99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton pause;
    private javax.swing.JButton restart;
    private javax.swing.JButton restart1;
    private javax.swing.JButton stop;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
