/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Geometric_Operations.java
 *
 * Created on May 27, 2012, 1:45:57 PM
 */
package $_School_Programs_12th_STD_SemI_$;

/**
 *
 * @author $Akshay$
 */
public class Geometric_Operations extends javax.swing.JFrame {

    /** Creates new form Geometric_Operations */
    public Geometric_Operations() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        i = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        base = new javax.swing.JTextField();
        button1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school_Program_Images/Shapes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 250, 110));

        Title.setFont(new java.awt.Font("Janda Curlygirl Chunky", 0, 22)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 204, 0));
        Title.setText("Area of Rectangle,Square & Triangle");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("<html> Enter a<br> Number </html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 40));

        i.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        i.setText("1");
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Height");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 210, 70, -1));

        height.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 80, 38));

        label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label.setText("Base");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, -1));

        base.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(base, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 80, 38));

        button1.setFont(new java.awt.Font("Hobo Std", 0, 20)); // NOI18N
        button1.setText("Calculate");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, 48));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ta.setColumns(20);
        ta.setRows(5);
        ta.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 80, 160));

        BG.setBackground(new java.awt.Color(123, 53, 250));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
int h = Integer.parseInt(height.getText());
int b = Integer.parseInt(base.getText());
int area = h*b;
int shape = Integer.parseInt(i.getText());
switch(shape)
{
case 1:    
ta.append("Area of Triangle is :"+area+"\n");
break;
case 2:    
ta.append("Area of Square is :"+area+"\n");
break;
case 3:    
ta.append("Area of Rectangle is :"+area+"\n");
break;
default:
ta.append("Invalid Number\n");
    break;
}        
    }//GEN-LAST:event_button1ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Geometric_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Geometric_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Geometric_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Geometric_Operations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Geometric_Operations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField base;
    private javax.swing.JButton button1;
    private javax.swing.JTextField height;
    private javax.swing.JTextField i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
