/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Grade_Total_Avg.java
 *
 * Created on May 26, 2012, 1:30:46 PM
 */
package $_School_Programs_12th_STD_SemI_$;

/**
 *
 * @author $Akshay$
 */
public class Grade_Total_Avg extends javax.swing.JFrame {

    /** Creates new form Grade_Total_Avg */
    public Grade_Total_Avg() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Maths");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 183, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Physics");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 134, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("English");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 85, -1, -1));

        m1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 77, 122, 38));

        m2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 126, 122, 38));

        m3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 175, 122, 38));

        m4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 224, 122, 38));

        m5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 268, 122, 38));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Chemistry");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 232, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("IP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 276, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ta.setColumns(13);
        ta.setRows(5);
        ta.setBorder(javax.swing.BorderFactory.createTitledBorder("Report"));
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, 230));

        jButton1.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        jButton1.setText("Creat Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 317, 172, 48));

        Title.setFont(new java.awt.Font("Annabel Script", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 204, 255));
        Title.setText("To Find Total, Average and Grade");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        BG.setBackground(new java.awt.Color(204, 102, 255));
        BG.setOpaque(true);
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int n1 = Integer.parseInt(m1.getText());
int n2 = Integer.parseInt(m2.getText());
int n3 = Integer.parseInt(m3.getText());
int n4 = Integer.parseInt(m4.getText());
int n5 = Integer.parseInt(m5.getText());
int sum = n1+n2+n3+n4+n5;
float avg = sum/5;
char grade = 'E';
if(avg<33) 
    grade = 'E';
else if(avg<50) 
    grade = 'D';
else if(avg<60)
    grade = 'C';
else if(avg<80)
    grade = 'B';
else if(avg<100)
    grade = 'A';
else
    grade = 'X';

        

ta.append("Total ="+sum+"\nAverage = "+avg+"\nGrade = "+grade);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grade_Total_Avg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grade_Total_Avg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grade_Total_Avg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grade_Total_Avg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Grade_Total_Avg().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
